%% AttributeChange [4mqualcom/apq8096[0m to [4m2.1[0m for node [4msoc-alarm[0m
%%  VOID -[0,53]->  soc-gate -[1,00]->  iot-controller -[0,53]->  soc-alarm -[0,08]-> soc-alarm-software 4,46 0,02
flowchart LR
	iot-controller[iot-controller]
	soc-gate[soc-gate]
	soc-alarm[soc-alarm]
	soc-alarm-software[soc-alarm-software]
	VOID[VOID]
	iot-controller -->|hasFirewall 0,20| soc-alarm
	iot-controller -->|isPhysicallySecured 0,20| soc-alarm
	iot-controller -->|softwareComponentIsEncrypted 0,20| soc-alarm
	iot-controller -->|!CVE-2022-25666 0,08| soc-alarm
	soc-gate -->|!firewall-risk 0,80| iot-controller
	soc-gate -->|!physically-secured-risk 0,80| iot-controller
	soc-gate -->|!software-encrypted-risk 0,80| iot-controller
	soc-gate -->|!CVE-2022-25666 0,08| iot-controller
	soc-gate -->|!CVE-2022-35927 0,39| iot-controller
	soc-alarm -->|!CVE-2022-25666 0,08| soc-alarm-software
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|isPhysicallySecured 0,20| soc-gate
	VOID -->|softwareComponentIsEncrypted 0,20| soc-gate