%% AttributeChange [4msoftwareComponentIsEncrypted[0m to [4mtrue[0m for node [4msoc-gate[0m
%%  VOID -[0,53]->  soc-gate -[0,53]->  iot-controller -[0,08]-> database 22,38 0,02
flowchart LR
	iot-controller[iot-controller]
	database[database]
	soc-gate[soc-gate]
	VOID[VOID]
	iot-controller -->|!CVE-2022-25666 0,08| database
	soc-gate -->|hasFirewall 0,20| iot-controller
	soc-gate -->|isPhysicallySecured 0,20| iot-controller
	soc-gate -->|softwareComponentIsEncrypted 0,20| iot-controller
	soc-gate -->|!CVE-2022-25666 0,08| iot-controller
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|isPhysicallySecured 0,20| soc-gate
	VOID -->|softwareComponentIsEncrypted 0,20| soc-gate