%% AttributeChange [4mcontiki-ng/contiki-ng[0m to [4m4.7[0m for node [4miot-controller[0m
%%  VOID -[0,93]->  soc-gate -[0,53]->  iot-controller -[0,08]-> database 39,28 0,04
flowchart LR
	iot-controller[iot-controller]
	database[database]
	soc-gate[soc-gate]
	VOID[VOID]
	iot-controller -->|!CVE-2022-25666 0,08| database
	soc-gate -->|hasFirewall 0,20| iot-controller
	soc-gate -->|isPhysicallySecured 0,20| iot-controller
	soc-gate -->|softwareComponentIsEncrypted 0,20| iot-controller
	soc-gate -->|!CVE-2022-25666 0,08| iot-controller
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|isPhysicallySecured 0,20| soc-gate
	VOID -->|!software-encrypted-risk 0,80| soc-gate
	VOID -->|!CVE-2022-35927 0,39| soc-gate