%% 1175000
flowchart LR
	soc-custom-59-software[soc-custom-59-software]
	soc-custom-9[soc-custom-9]
	soc-custom-92[soc-custom-92]
	soc-custom-93[soc-custom-93]
	soc-custom-90[soc-custom-90]
	soc-custom-7[soc-custom-7]
	soc-custom-91[soc-custom-91]
	soc-custom-8[soc-custom-8]
	soc-custom-77-software[soc-custom-77-software]
	soc-custom-16-software[soc-custom-16-software]
	soc-alarm[soc-alarm]
	soc-custom-96[soc-custom-96]
	soc-custom-97[soc-custom-97]
	soc-custom-94[soc-custom-94]
	soc-custom-95[soc-custom-95]
	soc-custom-34-software[soc-custom-34-software]
	soc-custom-98[soc-custom-98]
	soc-custom-90-software[soc-custom-90-software]
	soc-custom-99[soc-custom-99]
	soc-custom-5-software[soc-custom-5-software]
	soc-custom-26-software[soc-custom-26-software]
	soc-custom-49-software[soc-custom-49-software]
	soc-custom-67-software[soc-custom-67-software]
	desktop-software[desktop-software]
	soc-custom-80-software[soc-custom-80-software]
	soc-light[soc-light]
	soc-custom-44-software[soc-custom-44-software]
	soc-custom-62-software[soc-custom-62-software]
	soc-custom-85-software[soc-custom-85-software]
	soc-custom-70[soc-custom-70]
	cloud-printer[cloud-printer]
	soc-custom-97-software[soc-custom-97-software]
	soc-custom-71[soc-custom-71]
	soc-custom-39-software[soc-custom-39-software]
	soc-custom-70-software[soc-custom-70-software]
	soc-custom-42-software[soc-custom-42-software]
	soc-custom-36-software[soc-custom-36-software]
	cloud-notification-software[cloud-notification-software]
	soc-custom-74[soc-custom-74]
	soc-custom-75[soc-custom-75]
	soc-alarm-software[soc-alarm-software]
	soc-custom-72[soc-custom-72]
	soc-custom-73[soc-custom-73]
	soc-custom-78[soc-custom-78]
	soc-custom-7-software[soc-custom-7-software]
	soc-custom-79[soc-custom-79]
	soc-custom-76[soc-custom-76]
	soc-custom-77[soc-custom-77]
	soc-custom-75-software[soc-custom-75-software]
	soc-custom-72-software[soc-custom-72-software]
	soc-custom-81[soc-custom-81]
	soc-custom-69-software[soc-custom-69-software]
	soc-custom-82[soc-custom-82]
	soc-custom-80[soc-custom-80]
	soc-custom-2-software[soc-custom-2-software]
	soc-custom-64-software[soc-custom-64-software]
	soc-smoke[soc-smoke]
	soc-gate-software[soc-gate-software]
	soc-custom-85[soc-custom-85]
	soc-custom-47-software[soc-custom-47-software]
	soc-custom-100-software[soc-custom-100-software]
	soc-custom-86[soc-custom-86]
	soc-custom-83[soc-custom-83]
	soc-custom-84[soc-custom-84]
	soc-custom-89[soc-custom-89]
	soc-custom-87[soc-custom-87]
	soc-custom-88[soc-custom-88]
	soc-temperature[soc-temperature]
	soc-custom-56-software[soc-custom-56-software]
	soc-custom-65-software[soc-custom-65-software]
	soc-custom-28-software[soc-custom-28-software]
	soc-custom-93-software[soc-custom-93-software]
	soc-custom-84-software[soc-custom-84-software]
	soc-custom-40-software[soc-custom-40-software]
	soc-custom-14-software[soc-custom-14-software]
	soc-custom-37-software[soc-custom-37-software]
	soc-custom-55-software[soc-custom-55-software]
	soc-custom-74-software[soc-custom-74-software]
	soc-smoke-software[soc-smoke-software]
	soc-custom-21-software[soc-custom-21-software]
	soc-custom-27-software[soc-custom-27-software]
	soc-custom-33-software[soc-custom-33-software]
	soc-custom-24-software[soc-custom-24-software]
	soc-custom-18-software[soc-custom-18-software]
	soc-custom-1-software[soc-custom-1-software]
	soc-door-lock-software[soc-door-lock-software]
	soc-custom-52-software[soc-custom-52-software]
	soc-custom-11-software[soc-custom-11-software]
	soc-motion-software[soc-motion-software]
	soc-custom-46-software[soc-custom-46-software]
	soc-gate[soc-gate]
	cloud-weather[cloud-weather]
	soc-custom-8-software[soc-custom-8-software]
	soc-custom-87-software[soc-custom-87-software]
	desktop[desktop]
	server-software[server-software]
	soc-custom-5[soc-custom-5]
	soc-custom-6[soc-custom-6]
	soc-custom-3[soc-custom-3]
	soc-custom-4[soc-custom-4]
	soc-custom-71-software[soc-custom-71-software]
	soc-custom-1[soc-custom-1]
	soc-custom-30-software[soc-custom-30-software]
	soc-custom-2[soc-custom-2]
	printer[printer]
	soc-custom-10-software[soc-custom-10-software]
	soc-custom-68-software[soc-custom-68-software]
	soc-custom-16[soc-custom-16]
	soc-custom-96-software[soc-custom-96-software]
	soc-custom-17[soc-custom-17]
	soc-custom-14[soc-custom-14]
	soc-custom-15[soc-custom-15]
	soc-custom-86-software[soc-custom-86-software]
	soc-custom-18[soc-custom-18]
	soc-custom-19[soc-custom-19]
	soc-custom-81-software[soc-custom-81-software]
	soc-custom-12[soc-custom-12]
	soc-custom-25-software[soc-custom-25-software]
	soc-custom-13[soc-custom-13]
	soc-custom-10[soc-custom-10]
	soc-custom-11[soc-custom-11]
	soc-custom-43-software[soc-custom-43-software]
	soc-custom-63-software[soc-custom-63-software]
	soc-custom-78-software[soc-custom-78-software]
	soc-custom-20-software[soc-custom-20-software]
	soc-custom-27[soc-custom-27]
	soc-custom-28[soc-custom-28]
	soc-custom-25[soc-custom-25]
	soc-custom-26[soc-custom-26]
	database[database]
	soc-custom-29[soc-custom-29]
	soc-custom-6-software[soc-custom-6-software]
	soc-custom-15-software[soc-custom-15-software]
	soc-custom-20[soc-custom-20]
	soc-custom-23[soc-custom-23]
	soc-custom-24[soc-custom-24]
	soc-custom-21[soc-custom-21]
	soc-custom-22[soc-custom-22]
	soc-custom-88-software[soc-custom-88-software]
	soc-custom-100[soc-custom-100]
	soc-custom-91-software[soc-custom-91-software]
	soc-custom-4-software[soc-custom-4-software]
	soc-custom-61-software[soc-custom-61-software]
	soc-motion[soc-motion]
	soc-humidity-software[soc-humidity-software]
	soc-custom-45-software[soc-custom-45-software]
	soc-humidity[soc-humidity]
	soc-custom-66-software[soc-custom-66-software]
	server[server]
	cloud-notification[cloud-notification]
	soc-custom-17-software[soc-custom-17-software]
	soc-custom-58-software[soc-custom-58-software]
	soc-custom-83-software[soc-custom-83-software]
	soc-light-software[soc-light-software]
	soc-custom-23-software[soc-custom-23-software]
	soc-custom-99-software[soc-custom-99-software]
	soc-custom-9-software[soc-custom-9-software]
	soc-custom-12-software[soc-custom-12-software]
	soc-custom-94-software[soc-custom-94-software]
	soc-custom-53-software[soc-custom-53-software]
	soc-custom-50-software[soc-custom-50-software]
	soc-custom-41-software[soc-custom-41-software]
	soc-custom-58[soc-custom-58]
	soc-custom-19-software[soc-custom-19-software]
	soc-custom-59[soc-custom-59]
	soc-custom-89-software[soc-custom-89-software]
	soc-custom-13-software[soc-custom-13-software]
	soc-custom-22-software[soc-custom-22-software]
	soc-custom-52[soc-custom-52]
	soc-custom-53[soc-custom-53]
	soc-custom-50[soc-custom-50]
	iot-controller-software[iot-controller-software]
	soc-custom-31-software[soc-custom-31-software]
	VOID[VOID]
	soc-custom-51[soc-custom-51]
	soc-custom-56[soc-custom-56]
	soc-custom-57[soc-custom-57]
	soc-custom-98-software[soc-custom-98-software]
	soc-custom-54[soc-custom-54]
	soc-custom-55[soc-custom-55]
	iot-controller[iot-controller]
	soc-temperature-software[soc-temperature-software]
	soc-custom-60[soc-custom-60]
	soc-custom-51-software[soc-custom-51-software]
	soc-custom-92-software[soc-custom-92-software]
	soc-custom-32-software[soc-custom-32-software]
	soc-custom-69[soc-custom-69]
	router[router]
	cloud-printer-software[cloud-printer-software]
	soc-custom-63[soc-custom-63]
	soc-custom-79-software[soc-custom-79-software]
	soc-custom-64[soc-custom-64]
	cloud-weather-software[cloud-weather-software]
	soc-custom-61[soc-custom-61]
	soc-custom-62[soc-custom-62]
	soc-custom-67[soc-custom-67]
	soc-custom-68[soc-custom-68]
	soc-custom-65[soc-custom-65]
	soc-custom-66[soc-custom-66]
	soc-custom-38-software[soc-custom-38-software]
	soc-custom-82-software[soc-custom-82-software]
	soc-custom-73-software[soc-custom-73-software]
	soc-custom-38[soc-custom-38]
	soc-custom-39[soc-custom-39]
	soc-custom-36[soc-custom-36]
	soc-custom-37[soc-custom-37]
	soc-custom-48-software[soc-custom-48-software]
	soc-custom-54-software[soc-custom-54-software]
	soc-custom-30[soc-custom-30]
	soc-custom-31[soc-custom-31]
	soc-custom-34[soc-custom-34]
	soc-custom-57-software[soc-custom-57-software]
	soc-custom-35[soc-custom-35]
	soc-custom-32[soc-custom-32]
	soc-custom-33[soc-custom-33]
	soc-door-lock[soc-door-lock]
	soc-custom-95-software[soc-custom-95-software]
	soc-custom-60-software[soc-custom-60-software]
	soc-custom-49[soc-custom-49]
	soc-custom-35-software[soc-custom-35-software]
	soc-custom-47[soc-custom-47]
	soc-custom-48[soc-custom-48]
	soc-custom-41[soc-custom-41]
	soc-custom-42[soc-custom-42]
	soc-custom-76-software[soc-custom-76-software]
	printer-software[printer-software]
	soc-custom-29-software[soc-custom-29-software]
	soc-custom-40[soc-custom-40]
	soc-custom-45[soc-custom-45]
	soc-custom-46[soc-custom-46]
	soc-custom-43[soc-custom-43]
	soc-custom-44[soc-custom-44]
	soc-custom-3-software[soc-custom-3-software]
	soc-custom-59-software -->|!CVE-2022-35927 0,39| soc-custom-59
	soc-custom-9 -->|hasFirewall 0,20| iot-controller
	soc-custom-9 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-9 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-9 -->|!CVE-2022-25666 0,08| soc-custom-9-software
	soc-custom-9 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-9 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-92 -->|hasFirewall 0,20| iot-controller
	soc-custom-92 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-92 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-92 -->|!CVE-2022-25666 0,08| soc-custom-92-software
	soc-custom-92 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-92 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-93 -->|hasFirewall 0,20| iot-controller
	soc-custom-93 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-93 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-93 -->|!CVE-2022-25666 0,08| soc-custom-93-software
	soc-custom-93 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-93 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-90 -->|hasFirewall 0,20| iot-controller
	soc-custom-90 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-90 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-90 -->|!CVE-2022-25666 0,08| soc-custom-90-software
	soc-custom-90 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-90 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-7 -->|hasFirewall 0,20| iot-controller
	soc-custom-7 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-7 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-7 -->|!CVE-2022-25666 0,08| soc-custom-7-software
	soc-custom-7 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-7 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-91 -->|hasFirewall 0,20| iot-controller
	soc-custom-91 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-91 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-91 -->|!CVE-2022-25666 0,08| soc-custom-91-software
	soc-custom-91 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-91 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-8 -->|hasFirewall 0,20| iot-controller
	soc-custom-8 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-8 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-8 -->|!CVE-2022-25666 0,08| soc-custom-8-software
	soc-custom-8 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-8 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-77-software -->|!CVE-2022-35927 0,39| soc-custom-77
	soc-custom-16-software -->|!CVE-2022-35927 0,39| soc-custom-16
	soc-alarm -->|hasFirewall 0,20| iot-controller
	soc-alarm -->|isPhysicallySecured 0,20| iot-controller
	soc-alarm -->|!software-encrypted-risk 0,80| iot-controller
	soc-alarm -->|!CVE-2022-25666 0,08| soc-alarm-software
	soc-alarm -->|!CVE-2022-25666 0,08| iot-controller
	soc-alarm -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-96 -->|hasFirewall 0,20| iot-controller
	soc-custom-96 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-96 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-96 -->|!CVE-2022-25666 0,08| soc-custom-96-software
	soc-custom-96 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-96 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-97 -->|hasFirewall 0,20| iot-controller
	soc-custom-97 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-97 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-97 -->|!CVE-2022-25666 0,08| soc-custom-97-software
	soc-custom-97 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-97 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-94 -->|hasFirewall 0,20| iot-controller
	soc-custom-94 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-94 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-94 -->|!CVE-2022-25666 0,08| soc-custom-94-software
	soc-custom-94 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-94 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-95 -->|hasFirewall 0,20| iot-controller
	soc-custom-95 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-95 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-95 -->|!CVE-2022-25666 0,08| soc-custom-95-software
	soc-custom-95 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-95 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-34-software -->|!CVE-2022-35927 0,39| soc-custom-34
	soc-custom-98 -->|hasFirewall 0,20| iot-controller
	soc-custom-98 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-98 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-98 -->|!CVE-2022-25666 0,08| soc-custom-98-software
	soc-custom-98 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-98 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-90-software -->|!CVE-2022-35927 0,39| soc-custom-90
	soc-custom-99 -->|hasFirewall 0,20| iot-controller
	soc-custom-99 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-99 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-99 -->|!CVE-2022-25666 0,08| soc-custom-99-software
	soc-custom-99 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-99 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-5-software -->|!CVE-2022-35927 0,39| soc-custom-5
	soc-custom-26-software -->|!CVE-2022-35927 0,39| soc-custom-26
	soc-custom-49-software -->|!CVE-2022-35927 0,39| soc-custom-49
	soc-custom-67-software -->|!CVE-2022-35927 0,39| soc-custom-67
	soc-custom-80-software -->|!CVE-2022-35927 0,39| soc-custom-80
	soc-light -->|hasFirewall 0,20| iot-controller
	soc-light -->|isPhysicallySecured 0,20| iot-controller
	soc-light -->|!software-encrypted-risk 0,80| iot-controller
	soc-light -->|!CVE-2022-25666 0,08| soc-light-software
	soc-light -->|!CVE-2022-25666 0,08| iot-controller
	soc-light -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-44-software -->|!CVE-2022-35927 0,39| soc-custom-44
	soc-custom-62-software -->|!CVE-2022-35927 0,39| soc-custom-62
	soc-custom-85-software -->|!CVE-2022-35927 0,39| soc-custom-85
	soc-custom-70 -->|hasFirewall 0,20| iot-controller
	soc-custom-70 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-70 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-70 -->|!CVE-2022-25666 0,08| soc-custom-70-software
	soc-custom-70 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-70 -->|!CVE-2022-35927 0,39| iot-controller
	cloud-printer -->|!firewall-risk 0,80| router
	cloud-printer -->|!physically-secured-risk 0,80| router
	cloud-printer -->|!software-encrypted-risk 0,80| router
	soc-custom-97-software -->|!CVE-2022-35927 0,39| soc-custom-97
	soc-custom-71 -->|hasFirewall 0,20| iot-controller
	soc-custom-71 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-71 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-71 -->|!CVE-2022-25666 0,08| soc-custom-71-software
	soc-custom-71 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-71 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-39-software -->|!CVE-2022-35927 0,39| soc-custom-39
	soc-custom-70-software -->|!CVE-2022-35927 0,39| soc-custom-70
	soc-custom-42-software -->|!CVE-2022-35927 0,39| soc-custom-42
	soc-custom-36-software -->|!CVE-2022-35927 0,39| soc-custom-36
	soc-custom-74 -->|hasFirewall 0,20| iot-controller
	soc-custom-74 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-74 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-74 -->|!CVE-2022-25666 0,08| soc-custom-74-software
	soc-custom-74 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-74 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-75 -->|hasFirewall 0,20| iot-controller
	soc-custom-75 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-75 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-75 -->|!CVE-2022-25666 0,08| soc-custom-75-software
	soc-custom-75 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-75 -->|!CVE-2022-35927 0,39| iot-controller
	soc-alarm-software -->|!CVE-2022-35927 0,39| soc-alarm
	soc-custom-72 -->|hasFirewall 0,20| iot-controller
	soc-custom-72 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-72 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-72 -->|!CVE-2022-25666 0,08| soc-custom-72-software
	soc-custom-72 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-72 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-73 -->|hasFirewall 0,20| iot-controller
	soc-custom-73 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-73 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-73 -->|!CVE-2022-25666 0,08| soc-custom-73-software
	soc-custom-73 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-73 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-78 -->|hasFirewall 0,20| iot-controller
	soc-custom-78 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-78 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-78 -->|!CVE-2022-25666 0,08| soc-custom-78-software
	soc-custom-78 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-78 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-7-software -->|!CVE-2022-35927 0,39| soc-custom-7
	soc-custom-79 -->|hasFirewall 0,20| iot-controller
	soc-custom-79 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-79 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-79 -->|!CVE-2022-25666 0,08| soc-custom-79-software
	soc-custom-79 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-79 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-76 -->|hasFirewall 0,20| iot-controller
	soc-custom-76 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-76 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-76 -->|!CVE-2022-25666 0,08| soc-custom-76-software
	soc-custom-76 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-76 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-77 -->|hasFirewall 0,20| iot-controller
	soc-custom-77 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-77 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-77 -->|!CVE-2022-25666 0,08| soc-custom-77-software
	soc-custom-77 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-77 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-75-software -->|!CVE-2022-35927 0,39| soc-custom-75
	soc-custom-72-software -->|!CVE-2022-35927 0,39| soc-custom-72
	soc-custom-81 -->|hasFirewall 0,20| iot-controller
	soc-custom-81 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-81 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-81 -->|!CVE-2022-25666 0,08| soc-custom-81-software
	soc-custom-81 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-81 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-69-software -->|!CVE-2022-35927 0,39| soc-custom-69
	soc-custom-82 -->|hasFirewall 0,20| iot-controller
	soc-custom-82 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-82 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-82 -->|!CVE-2022-25666 0,08| soc-custom-82-software
	soc-custom-82 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-82 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-80 -->|hasFirewall 0,20| iot-controller
	soc-custom-80 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-80 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-80 -->|!CVE-2022-25666 0,08| soc-custom-80-software
	soc-custom-80 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-80 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-2-software -->|!CVE-2022-35927 0,39| soc-custom-2
	soc-custom-64-software -->|!CVE-2022-35927 0,39| soc-custom-64
	soc-smoke -->|hasFirewall 0,20| iot-controller
	soc-smoke -->|isPhysicallySecured 0,20| iot-controller
	soc-smoke -->|!software-encrypted-risk 0,80| iot-controller
	soc-smoke -->|!CVE-2022-25666 0,08| soc-smoke-software
	soc-smoke -->|!CVE-2022-25666 0,08| iot-controller
	soc-smoke -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-85 -->|hasFirewall 0,20| iot-controller
	soc-custom-85 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-85 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-85 -->|!CVE-2022-25666 0,08| soc-custom-85-software
	soc-custom-85 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-85 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-47-software -->|!CVE-2022-35927 0,39| soc-custom-47
	soc-custom-100-software -->|!CVE-2022-35927 0,39| soc-custom-100
	soc-custom-86 -->|hasFirewall 0,20| iot-controller
	soc-custom-86 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-86 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-86 -->|!CVE-2022-25666 0,08| soc-custom-86-software
	soc-custom-86 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-86 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-83 -->|hasFirewall 0,20| iot-controller
	soc-custom-83 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-83 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-83 -->|!CVE-2022-25666 0,08| soc-custom-83-software
	soc-custom-83 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-83 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-84 -->|hasFirewall 0,20| iot-controller
	soc-custom-84 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-84 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-84 -->|!CVE-2022-25666 0,08| soc-custom-84-software
	soc-custom-84 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-84 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-89 -->|hasFirewall 0,20| iot-controller
	soc-custom-89 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-89 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-89 -->|!CVE-2022-25666 0,08| soc-custom-89-software
	soc-custom-89 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-89 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-87 -->|hasFirewall 0,20| iot-controller
	soc-custom-87 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-87 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-87 -->|!CVE-2022-25666 0,08| soc-custom-87-software
	soc-custom-87 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-87 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-88 -->|hasFirewall 0,20| iot-controller
	soc-custom-88 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-88 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-88 -->|!CVE-2022-25666 0,08| soc-custom-88-software
	soc-custom-88 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-88 -->|!CVE-2022-35927 0,39| iot-controller
	soc-temperature -->|hasFirewall 0,20| iot-controller
	soc-temperature -->|isPhysicallySecured 0,20| iot-controller
	soc-temperature -->|!software-encrypted-risk 0,80| iot-controller
	soc-temperature -->|!CVE-2022-25666 0,08| soc-temperature-software
	soc-temperature -->|!CVE-2022-25666 0,08| iot-controller
	soc-temperature -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-56-software -->|!CVE-2022-35927 0,39| soc-custom-56
	soc-custom-65-software -->|!CVE-2022-35927 0,39| soc-custom-65
	soc-custom-28-software -->|!CVE-2022-35927 0,39| soc-custom-28
	soc-custom-93-software -->|!CVE-2022-35927 0,39| soc-custom-93
	soc-custom-84-software -->|!CVE-2022-35927 0,39| soc-custom-84
	soc-custom-40-software -->|!CVE-2022-35927 0,39| soc-custom-40
	soc-custom-14-software -->|!CVE-2022-35927 0,39| soc-custom-14
	soc-custom-37-software -->|!CVE-2022-35927 0,39| soc-custom-37
	soc-custom-55-software -->|!CVE-2022-35927 0,39| soc-custom-55
	soc-custom-74-software -->|!CVE-2022-35927 0,39| soc-custom-74
	soc-smoke-software -->|!CVE-2022-35927 0,39| soc-smoke
	soc-custom-21-software -->|!CVE-2022-35927 0,39| soc-custom-21
	soc-custom-27-software -->|!CVE-2022-35927 0,39| soc-custom-27
	soc-custom-33-software -->|!CVE-2022-35927 0,39| soc-custom-33
	soc-custom-24-software -->|!CVE-2022-35927 0,39| soc-custom-24
	soc-custom-18-software -->|!CVE-2022-35927 0,39| soc-custom-18
	soc-custom-1-software -->|!CVE-2022-35927 0,39| soc-custom-1
	soc-custom-52-software -->|!CVE-2022-35927 0,39| soc-custom-52
	soc-custom-11-software -->|!CVE-2022-35927 0,39| soc-custom-11
	soc-motion-software -->|!CVE-2022-35927 0,39| soc-motion
	soc-custom-46-software -->|!CVE-2022-35927 0,39| soc-custom-46
	soc-gate -->|hasFirewall 0,20| iot-controller
	soc-gate -->|isPhysicallySecured 0,20| iot-controller
	soc-gate -->|!software-encrypted-risk 0,80| iot-controller
	soc-gate -->|!CVE-2022-25666 0,08| soc-gate-software
	soc-gate -->|!CVE-2022-25666 0,08| iot-controller
	soc-gate -->|!CVE-2022-35927 0,39| iot-controller
	cloud-weather -->|!firewall-risk 0,80| router
	cloud-weather -->|!physically-secured-risk 0,80| router
	cloud-weather -->|!software-encrypted-risk 0,80| router
	soc-custom-8-software -->|!CVE-2022-35927 0,39| soc-custom-8
	soc-custom-87-software -->|!CVE-2022-35927 0,39| soc-custom-87
	desktop -->|hasFirewall 0,20| iot-controller
	desktop -->|isPhysicallySecured 0,20| iot-controller
	desktop -->|!software-encrypted-risk 0,80| iot-controller
	desktop -->|!CVE-2022-35927 0,39| iot-controller
	server-software -->|!CVE-2022-35927 0,39| server
	soc-custom-5 -->|hasFirewall 0,20| iot-controller
	soc-custom-5 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-5 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-5 -->|!CVE-2022-25666 0,08| soc-custom-5-software
	soc-custom-5 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-5 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-6 -->|hasFirewall 0,20| iot-controller
	soc-custom-6 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-6 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-6 -->|!CVE-2022-25666 0,08| soc-custom-6-software
	soc-custom-6 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-6 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-3 -->|hasFirewall 0,20| iot-controller
	soc-custom-3 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-3 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-3 -->|!CVE-2022-25666 0,08| soc-custom-3-software
	soc-custom-3 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-3 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-4 -->|hasFirewall 0,20| iot-controller
	soc-custom-4 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-4 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-4 -->|!CVE-2022-25666 0,08| soc-custom-4-software
	soc-custom-4 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-4 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-71-software -->|!CVE-2022-35927 0,39| soc-custom-71
	soc-custom-1 -->|hasFirewall 0,20| iot-controller
	soc-custom-1 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-1 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-1 -->|!CVE-2022-25666 0,08| soc-custom-1-software
	soc-custom-1 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-1 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-30-software -->|!CVE-2022-35927 0,39| soc-custom-30
	soc-custom-2 -->|hasFirewall 0,20| iot-controller
	soc-custom-2 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-2 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-2 -->|!CVE-2022-25666 0,08| soc-custom-2-software
	soc-custom-2 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-2 -->|!CVE-2022-35927 0,39| iot-controller
	printer -->|!firewall-risk 0,80| router
	printer -->|!physically-secured-risk 0,80| router
	printer -->|!software-encrypted-risk 0,80| router
	printer -->|!CVE-2022-25666 0,08| printer-software
	printer -->|!CVE-2022-25666 0,08| router
	soc-custom-10-software -->|!CVE-2022-35927 0,39| soc-custom-10
	soc-custom-68-software -->|!CVE-2022-35927 0,39| soc-custom-68
	soc-custom-16 -->|hasFirewall 0,20| iot-controller
	soc-custom-16 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-16 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-16 -->|!CVE-2022-25666 0,08| soc-custom-16-software
	soc-custom-16 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-16 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-96-software -->|!CVE-2022-35927 0,39| soc-custom-96
	soc-custom-17 -->|hasFirewall 0,20| iot-controller
	soc-custom-17 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-17 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-17 -->|!CVE-2022-25666 0,08| soc-custom-17-software
	soc-custom-17 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-17 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-14 -->|hasFirewall 0,20| iot-controller
	soc-custom-14 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-14 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-14 -->|!CVE-2022-25666 0,08| soc-custom-14-software
	soc-custom-14 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-14 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-15 -->|hasFirewall 0,20| iot-controller
	soc-custom-15 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-15 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-15 -->|!CVE-2022-25666 0,08| soc-custom-15-software
	soc-custom-15 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-15 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-86-software -->|!CVE-2022-35927 0,39| soc-custom-86
	soc-custom-18 -->|hasFirewall 0,20| iot-controller
	soc-custom-18 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-18 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-18 -->|!CVE-2022-25666 0,08| soc-custom-18-software
	soc-custom-18 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-18 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-19 -->|hasFirewall 0,20| iot-controller
	soc-custom-19 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-19 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-19 -->|!CVE-2022-25666 0,08| soc-custom-19-software
	soc-custom-19 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-19 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-81-software -->|!CVE-2022-35927 0,39| soc-custom-81
	soc-custom-12 -->|hasFirewall 0,20| iot-controller
	soc-custom-12 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-12 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-12 -->|!CVE-2022-25666 0,08| soc-custom-12-software
	soc-custom-12 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-12 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-25-software -->|!CVE-2022-35927 0,39| soc-custom-25
	soc-custom-13 -->|hasFirewall 0,20| iot-controller
	soc-custom-13 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-13 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-13 -->|!CVE-2022-25666 0,08| soc-custom-13-software
	soc-custom-13 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-13 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-10 -->|hasFirewall 0,20| iot-controller
	soc-custom-10 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-10 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-10 -->|!CVE-2022-25666 0,08| soc-custom-10-software
	soc-custom-10 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-10 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-11 -->|hasFirewall 0,20| iot-controller
	soc-custom-11 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-11 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-11 -->|!CVE-2022-25666 0,08| soc-custom-11-software
	soc-custom-11 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-11 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-43-software -->|!CVE-2022-35927 0,39| soc-custom-43
	soc-custom-63-software -->|!CVE-2022-35927 0,39| soc-custom-63
	soc-custom-78-software -->|!CVE-2022-35927 0,39| soc-custom-78
	soc-custom-20-software -->|!CVE-2022-35927 0,39| soc-custom-20
	soc-custom-27 -->|hasFirewall 0,20| iot-controller
	soc-custom-27 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-27 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-27 -->|!CVE-2022-25666 0,08| soc-custom-27-software
	soc-custom-27 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-27 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-28 -->|hasFirewall 0,20| iot-controller
	soc-custom-28 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-28 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-28 -->|!CVE-2022-25666 0,08| soc-custom-28-software
	soc-custom-28 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-28 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-25 -->|hasFirewall 0,20| iot-controller
	soc-custom-25 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-25 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-25 -->|!CVE-2022-25666 0,08| soc-custom-25-software
	soc-custom-25 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-25 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-26 -->|hasFirewall 0,20| iot-controller
	soc-custom-26 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-26 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-26 -->|!CVE-2022-25666 0,08| soc-custom-26-software
	soc-custom-26 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-26 -->|!CVE-2022-35927 0,39| iot-controller
	database -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-29 -->|hasFirewall 0,20| iot-controller
	soc-custom-29 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-29 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-29 -->|!CVE-2022-25666 0,08| soc-custom-29-software
	soc-custom-29 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-29 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-6-software -->|!CVE-2022-35927 0,39| soc-custom-6
	soc-custom-15-software -->|!CVE-2022-35927 0,39| soc-custom-15
	soc-custom-20 -->|hasFirewall 0,20| iot-controller
	soc-custom-20 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-20 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-20 -->|!CVE-2022-25666 0,08| soc-custom-20-software
	soc-custom-20 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-20 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-23 -->|hasFirewall 0,20| iot-controller
	soc-custom-23 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-23 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-23 -->|!CVE-2022-25666 0,08| soc-custom-23-software
	soc-custom-23 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-23 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-24 -->|hasFirewall 0,20| iot-controller
	soc-custom-24 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-24 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-24 -->|!CVE-2022-25666 0,08| soc-custom-24-software
	soc-custom-24 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-24 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-21 -->|hasFirewall 0,20| iot-controller
	soc-custom-21 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-21 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-21 -->|!CVE-2022-25666 0,08| soc-custom-21-software
	soc-custom-21 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-21 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-22 -->|hasFirewall 0,20| iot-controller
	soc-custom-22 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-22 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-22 -->|!CVE-2022-25666 0,08| soc-custom-22-software
	soc-custom-22 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-22 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-88-software -->|!CVE-2022-35927 0,39| soc-custom-88
	soc-custom-100 -->|hasFirewall 0,20| iot-controller
	soc-custom-100 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-100 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-100 -->|!CVE-2022-25666 0,08| soc-custom-100-software
	soc-custom-100 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-100 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-91-software -->|!CVE-2022-35927 0,39| soc-custom-91
	soc-custom-4-software -->|!CVE-2022-35927 0,39| soc-custom-4
	soc-custom-61-software -->|!CVE-2022-35927 0,39| soc-custom-61
	soc-motion -->|hasFirewall 0,20| iot-controller
	soc-motion -->|isPhysicallySecured 0,20| iot-controller
	soc-motion -->|!software-encrypted-risk 0,80| iot-controller
	soc-motion -->|!CVE-2022-25666 0,08| soc-motion-software
	soc-motion -->|!CVE-2022-25666 0,08| iot-controller
	soc-motion -->|!CVE-2022-35927 0,39| iot-controller
	soc-humidity-software -->|!CVE-2022-35927 0,39| soc-humidity
	soc-custom-45-software -->|!CVE-2022-35927 0,39| soc-custom-45
	soc-humidity -->|hasFirewall 0,20| iot-controller
	soc-humidity -->|isPhysicallySecured 0,20| iot-controller
	soc-humidity -->|!software-encrypted-risk 0,80| iot-controller
	soc-humidity -->|!CVE-2022-25666 0,08| soc-humidity-software
	soc-humidity -->|!CVE-2022-25666 0,08| iot-controller
	soc-humidity -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-66-software -->|!CVE-2022-35927 0,39| soc-custom-66
	server -->|!CVE-2022-25666 0,08| server-software
	cloud-notification -->|!firewall-risk 0,80| router
	cloud-notification -->|!physically-secured-risk 0,80| router
	cloud-notification -->|!software-encrypted-risk 0,80| router
	soc-custom-17-software -->|!CVE-2022-35927 0,39| soc-custom-17
	soc-custom-58-software -->|!CVE-2022-35927 0,39| soc-custom-58
	soc-custom-83-software -->|!CVE-2022-35927 0,39| soc-custom-83
	soc-light-software -->|!CVE-2022-35927 0,39| soc-light
	soc-custom-23-software -->|!CVE-2022-35927 0,39| soc-custom-23
	soc-custom-99-software -->|!CVE-2022-35927 0,39| soc-custom-99
	soc-custom-9-software -->|!CVE-2022-35927 0,39| soc-custom-9
	soc-custom-12-software -->|!CVE-2022-35927 0,39| soc-custom-12
	soc-custom-94-software -->|!CVE-2022-35927 0,39| soc-custom-94
	soc-custom-53-software -->|!CVE-2022-35927 0,39| soc-custom-53
	soc-custom-50-software -->|!CVE-2022-35927 0,39| soc-custom-50
	soc-custom-41-software -->|!CVE-2022-35927 0,39| soc-custom-41
	soc-custom-58 -->|hasFirewall 0,20| iot-controller
	soc-custom-58 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-58 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-58 -->|!CVE-2022-25666 0,08| soc-custom-58-software
	soc-custom-58 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-58 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-19-software -->|!CVE-2022-35927 0,39| soc-custom-19
	soc-custom-59 -->|hasFirewall 0,20| iot-controller
	soc-custom-59 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-59 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-59 -->|!CVE-2022-25666 0,08| soc-custom-59-software
	soc-custom-59 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-59 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-89-software -->|!CVE-2022-35927 0,39| soc-custom-89
	soc-custom-13-software -->|!CVE-2022-35927 0,39| soc-custom-13
	soc-custom-22-software -->|!CVE-2022-35927 0,39| soc-custom-22
	soc-custom-52 -->|hasFirewall 0,20| iot-controller
	soc-custom-52 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-52 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-52 -->|!CVE-2022-25666 0,08| soc-custom-52-software
	soc-custom-52 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-52 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-53 -->|hasFirewall 0,20| iot-controller
	soc-custom-53 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-53 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-53 -->|!CVE-2022-25666 0,08| soc-custom-53-software
	soc-custom-53 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-53 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-50 -->|hasFirewall 0,20| iot-controller
	soc-custom-50 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-50 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-50 -->|!CVE-2022-25666 0,08| soc-custom-50-software
	soc-custom-50 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-50 -->|!CVE-2022-35927 0,39| iot-controller
	iot-controller-software -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-31-software -->|!CVE-2022-35927 0,39| soc-custom-31
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|!uncertainty-entry 0,08| printer
	VOID -->|!uncertainty-entry 0,08| server
	VOID -->|!uncertainty-entry 0,08| iot-controller
	VOID -->|!uncertainty-entry 0,08| router
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|!firewall-risk 0,80| printer
	VOID -->|!firewall-risk 0,80| server
	VOID -->|hasFirewall 0,20| iot-controller
	VOID -->|!firewall-risk 0,80| router
	VOID -->|isPhysicallySecured 0,20| soc-gate
	VOID -->|!physically-secured-risk 0,80| printer
	VOID -->|!physically-secured-risk 0,80| server
	VOID -->|isPhysicallySecured 0,20| iot-controller
	VOID -->|!physically-secured-risk 0,80| router
	VOID -->|softwareComponentIsEncrypted 0,20| soc-gate
	VOID -->|!software-encrypted-risk 0,80| printer
	VOID -->|!software-encrypted-risk 0,80| server
	VOID -->|!software-encrypted-risk 0,80| iot-controller
	VOID -->|!software-encrypted-risk 0,80| router
	VOID -->|!CVE-2022-35927 0,39| printer
	VOID -->|!CVE-2022-35927 0,39| server
	VOID -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-51 -->|hasFirewall 0,20| iot-controller
	soc-custom-51 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-51 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-51 -->|!CVE-2022-25666 0,08| soc-custom-51-software
	soc-custom-51 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-51 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-56 -->|hasFirewall 0,20| iot-controller
	soc-custom-56 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-56 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-56 -->|!CVE-2022-25666 0,08| soc-custom-56-software
	soc-custom-56 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-56 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-57 -->|hasFirewall 0,20| iot-controller
	soc-custom-57 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-57 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-57 -->|!CVE-2022-25666 0,08| soc-custom-57-software
	soc-custom-57 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-57 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-98-software -->|!CVE-2022-35927 0,39| soc-custom-98
	soc-custom-54 -->|hasFirewall 0,20| iot-controller
	soc-custom-54 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-54 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-54 -->|!CVE-2022-25666 0,08| soc-custom-54-software
	soc-custom-54 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-54 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-55 -->|hasFirewall 0,20| iot-controller
	soc-custom-55 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-55 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-55 -->|!CVE-2022-25666 0,08| soc-custom-55-software
	soc-custom-55 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-55 -->|!CVE-2022-35927 0,39| iot-controller
	iot-controller -->|!firewall-risk 0,80| soc-custom-9
	iot-controller -->|!firewall-risk 0,80| soc-custom-92
	iot-controller -->|!firewall-risk 0,80| soc-custom-93
	iot-controller -->|!firewall-risk 0,80| soc-custom-90
	iot-controller -->|!firewall-risk 0,80| soc-custom-7
	iot-controller -->|!firewall-risk 0,80| soc-custom-8
	iot-controller -->|!firewall-risk 0,80| soc-custom-91
	iot-controller -->|!firewall-risk 0,80| soc-alarm
	iot-controller -->|!firewall-risk 0,80| soc-custom-96
	iot-controller -->|!firewall-risk 0,80| soc-custom-97
	iot-controller -->|!firewall-risk 0,80| soc-custom-94
	iot-controller -->|!firewall-risk 0,80| soc-custom-95
	iot-controller -->|!firewall-risk 0,80| soc-custom-98
	iot-controller -->|!firewall-risk 0,80| soc-custom-99
	iot-controller -->|!firewall-risk 0,80| soc-light
	iot-controller -->|!firewall-risk 0,80| soc-custom-70
	iot-controller -->|!firewall-risk 0,80| soc-custom-71
	iot-controller -->|!firewall-risk 0,80| soc-custom-74
	iot-controller -->|!firewall-risk 0,80| soc-custom-75
	iot-controller -->|!firewall-risk 0,80| soc-custom-72
	iot-controller -->|!firewall-risk 0,80| soc-custom-73
	iot-controller -->|!firewall-risk 0,80| soc-custom-78
	iot-controller -->|!firewall-risk 0,80| soc-custom-79
	iot-controller -->|!firewall-risk 0,80| soc-custom-76
	iot-controller -->|!firewall-risk 0,80| soc-custom-77
	iot-controller -->|!firewall-risk 0,80| soc-custom-81
	iot-controller -->|!firewall-risk 0,80| soc-custom-82
	iot-controller -->|!firewall-risk 0,80| soc-custom-80
	iot-controller -->|!firewall-risk 0,80| soc-smoke
	iot-controller -->|!firewall-risk 0,80| soc-custom-85
	iot-controller -->|!firewall-risk 0,80| soc-custom-86
	iot-controller -->|!firewall-risk 0,80| soc-custom-83
	iot-controller -->|!firewall-risk 0,80| soc-custom-84
	iot-controller -->|!firewall-risk 0,80| soc-custom-89
	iot-controller -->|!firewall-risk 0,80| soc-custom-87
	iot-controller -->|!firewall-risk 0,80| soc-custom-88
	iot-controller -->|!firewall-risk 0,80| soc-temperature
	iot-controller -->|hasFirewall 0,20| soc-gate
	iot-controller -->|!firewall-risk 0,80| desktop
	iot-controller -->|!firewall-risk 0,80| soc-custom-5
	iot-controller -->|!firewall-risk 0,80| soc-custom-6
	iot-controller -->|!firewall-risk 0,80| soc-custom-3
	iot-controller -->|!firewall-risk 0,80| soc-custom-4
	iot-controller -->|!firewall-risk 0,80| soc-custom-1
	iot-controller -->|!firewall-risk 0,80| soc-custom-2
	iot-controller -->|!firewall-risk 0,80| soc-custom-16
	iot-controller -->|!firewall-risk 0,80| soc-custom-17
	iot-controller -->|!firewall-risk 0,80| soc-custom-14
	iot-controller -->|!firewall-risk 0,80| soc-custom-15
	iot-controller -->|!firewall-risk 0,80| soc-custom-18
	iot-controller -->|!firewall-risk 0,80| soc-custom-19
	iot-controller -->|!firewall-risk 0,80| soc-custom-12
	iot-controller -->|!firewall-risk 0,80| soc-custom-13
	iot-controller -->|!firewall-risk 0,80| soc-custom-10
	iot-controller -->|!firewall-risk 0,80| soc-custom-11
	iot-controller -->|!firewall-risk 0,80| soc-custom-27
	iot-controller -->|!firewall-risk 0,80| soc-custom-28
	iot-controller -->|!firewall-risk 0,80| soc-custom-25
	iot-controller -->|!firewall-risk 0,80| soc-custom-26
	iot-controller -->|!firewall-risk 0,80| soc-custom-29
	iot-controller -->|!firewall-risk 0,80| soc-custom-20
	iot-controller -->|!firewall-risk 0,80| soc-custom-23
	iot-controller -->|!firewall-risk 0,80| soc-custom-24
	iot-controller -->|!firewall-risk 0,80| soc-custom-21
	iot-controller -->|!firewall-risk 0,80| soc-custom-22
	iot-controller -->|!firewall-risk 0,80| soc-custom-100
	iot-controller -->|!firewall-risk 0,80| soc-motion
	iot-controller -->|!firewall-risk 0,80| soc-humidity
	iot-controller -->|!firewall-risk 0,80| soc-custom-58
	iot-controller -->|!firewall-risk 0,80| soc-custom-59
	iot-controller -->|!firewall-risk 0,80| soc-custom-52
	iot-controller -->|!firewall-risk 0,80| soc-custom-53
	iot-controller -->|!firewall-risk 0,80| soc-custom-50
	iot-controller -->|!firewall-risk 0,80| soc-custom-51
	iot-controller -->|!firewall-risk 0,80| soc-custom-56
	iot-controller -->|!firewall-risk 0,80| soc-custom-57
	iot-controller -->|!firewall-risk 0,80| soc-custom-54
	iot-controller -->|!firewall-risk 0,80| soc-custom-55
	iot-controller -->|!firewall-risk 0,80| soc-custom-60
	iot-controller -->|!firewall-risk 0,80| soc-custom-69
	iot-controller -->|!firewall-risk 0,80| router
	iot-controller -->|!firewall-risk 0,80| soc-custom-63
	iot-controller -->|!firewall-risk 0,80| soc-custom-64
	iot-controller -->|!firewall-risk 0,80| soc-custom-61
	iot-controller -->|!firewall-risk 0,80| soc-custom-62
	iot-controller -->|!firewall-risk 0,80| soc-custom-67
	iot-controller -->|!firewall-risk 0,80| soc-custom-68
	iot-controller -->|!firewall-risk 0,80| soc-custom-65
	iot-controller -->|!firewall-risk 0,80| soc-custom-66
	iot-controller -->|!firewall-risk 0,80| soc-custom-38
	iot-controller -->|!firewall-risk 0,80| soc-custom-39
	iot-controller -->|!firewall-risk 0,80| soc-custom-36
	iot-controller -->|!firewall-risk 0,80| soc-custom-37
	iot-controller -->|!firewall-risk 0,80| soc-custom-30
	iot-controller -->|!firewall-risk 0,80| soc-custom-31
	iot-controller -->|!firewall-risk 0,80| soc-custom-34
	iot-controller -->|!firewall-risk 0,80| soc-custom-35
	iot-controller -->|!firewall-risk 0,80| soc-custom-32
	iot-controller -->|!firewall-risk 0,80| soc-custom-33
	iot-controller -->|hasFirewall 0,20| soc-door-lock
	iot-controller -->|!firewall-risk 0,80| soc-custom-49
	iot-controller -->|!firewall-risk 0,80| soc-custom-47
	iot-controller -->|!firewall-risk 0,80| soc-custom-48
	iot-controller -->|!firewall-risk 0,80| soc-custom-41
	iot-controller -->|!firewall-risk 0,80| soc-custom-42
	iot-controller -->|!firewall-risk 0,80| soc-custom-40
	iot-controller -->|!firewall-risk 0,80| soc-custom-45
	iot-controller -->|!firewall-risk 0,80| soc-custom-46
	iot-controller -->|!firewall-risk 0,80| soc-custom-43
	iot-controller -->|!firewall-risk 0,80| soc-custom-44
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-9
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-92
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-93
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-90
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-7
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-8
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-91
	iot-controller -->|!physically-secured-risk 0,80| soc-alarm
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-96
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-97
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-94
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-95
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-98
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-99
	iot-controller -->|!physically-secured-risk 0,80| soc-light
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-70
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-71
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-74
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-75
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-72
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-73
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-78
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-79
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-76
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-77
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-81
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-82
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-80
	iot-controller -->|!physically-secured-risk 0,80| soc-smoke
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-85
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-86
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-83
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-84
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-89
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-87
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-88
	iot-controller -->|!physically-secured-risk 0,80| soc-temperature
	iot-controller -->|isPhysicallySecured 0,20| soc-gate
	iot-controller -->|!physically-secured-risk 0,80| desktop
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-5
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-6
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-3
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-4
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-1
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-2
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-16
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-17
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-14
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-15
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-18
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-19
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-12
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-13
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-10
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-11
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-27
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-28
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-25
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-26
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-29
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-20
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-23
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-24
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-21
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-22
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-100
	iot-controller -->|!physically-secured-risk 0,80| soc-motion
	iot-controller -->|!physically-secured-risk 0,80| soc-humidity
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-58
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-59
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-52
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-53
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-50
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-51
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-56
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-57
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-54
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-55
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-60
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-69
	iot-controller -->|!physically-secured-risk 0,80| router
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-63
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-64
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-61
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-62
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-67
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-68
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-65
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-66
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-38
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-39
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-36
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-37
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-30
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-31
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-34
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-35
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-32
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-33
	iot-controller -->|isPhysicallySecured 0,20| soc-door-lock
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-49
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-47
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-48
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-41
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-42
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-40
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-45
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-46
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-43
	iot-controller -->|!physically-secured-risk 0,80| soc-custom-44
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-9
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-92
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-93
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-90
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-7
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-8
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-91
	iot-controller -->|!software-encrypted-risk 0,80| soc-alarm
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-96
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-97
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-94
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-95
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-98
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-99
	iot-controller -->|!software-encrypted-risk 0,80| soc-light
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-70
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-71
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-74
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-75
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-72
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-73
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-78
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-79
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-76
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-77
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-81
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-82
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-80
	iot-controller -->|!software-encrypted-risk 0,80| soc-smoke
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-85
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-86
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-83
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-84
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-89
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-87
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-88
	iot-controller -->|!software-encrypted-risk 0,80| soc-temperature
	iot-controller -->|softwareComponentIsEncrypted 0,20| soc-gate
	iot-controller -->|!software-encrypted-risk 0,80| desktop
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-5
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-6
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-3
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-4
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-1
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-2
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-16
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-17
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-14
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-15
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-18
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-19
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-12
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-13
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-10
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-11
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-27
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-28
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-25
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-26
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-29
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-20
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-23
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-24
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-21
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-22
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-100
	iot-controller -->|!software-encrypted-risk 0,80| soc-motion
	iot-controller -->|!software-encrypted-risk 0,80| soc-humidity
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-58
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-59
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-52
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-53
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-50
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-51
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-56
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-57
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-54
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-55
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-60
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-69
	iot-controller -->|!software-encrypted-risk 0,80| router
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-63
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-64
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-61
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-62
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-67
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-68
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-65
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-66
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-38
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-39
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-36
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-37
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-30
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-31
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-34
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-35
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-32
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-33
	iot-controller -->|softwareComponentIsEncrypted 0,20| soc-door-lock
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-49
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-47
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-48
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-41
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-42
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-40
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-45
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-46
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-43
	iot-controller -->|!software-encrypted-risk 0,80| soc-custom-44
	iot-controller -->|!CVE-2022-25666 0,08| iot-controller-software
	iot-controller -->|!CVE-2022-25666 0,08| database
	iot-controller -->|!CVE-2022-25666 0,08| soc-motion
	iot-controller -->|!CVE-2022-25666 0,08| soc-humidity
	iot-controller -->|!CVE-2022-25666 0,08| soc-door-lock
	iot-controller -->|!CVE-2022-25666 0,08| soc-gate
	iot-controller -->|!CVE-2022-25666 0,08| soc-alarm
	iot-controller -->|!CVE-2022-25666 0,08| soc-smoke
	iot-controller -->|!CVE-2022-25666 0,08| soc-temperature
	iot-controller -->|!CVE-2022-25666 0,08| soc-light
	iot-controller -->|!CVE-2022-25666 0,08| router
	iot-controller -->|!CVE-2022-25666 0,08| desktop
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-1
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-2
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-3
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-4
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-5
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-6
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-7
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-8
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-9
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-10
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-11
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-12
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-13
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-14
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-15
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-16
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-17
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-18
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-19
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-20
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-21
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-22
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-23
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-24
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-25
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-26
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-27
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-28
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-29
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-30
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-31
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-32
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-33
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-34
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-35
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-36
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-37
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-38
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-39
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-40
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-41
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-42
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-43
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-44
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-45
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-46
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-47
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-48
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-49
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-50
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-51
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-52
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-53
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-54
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-55
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-56
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-57
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-58
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-59
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-60
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-61
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-62
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-63
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-64
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-65
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-66
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-67
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-68
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-69
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-70
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-71
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-72
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-73
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-74
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-75
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-76
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-77
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-78
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-79
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-80
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-81
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-82
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-83
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-84
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-85
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-86
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-87
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-88
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-89
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-90
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-91
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-92
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-93
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-94
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-95
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-96
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-97
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-98
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-99
	iot-controller -->|!CVE-2022-25666 0,08| soc-custom-100
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-9
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-92
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-93
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-90
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-7
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-8
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-91
	iot-controller -->|!CVE-2022-35927 0,39| soc-alarm
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-96
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-97
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-94
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-95
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-98
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-99
	iot-controller -->|!CVE-2022-35927 0,39| soc-light
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-70
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-71
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-74
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-75
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-72
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-73
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-78
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-79
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-76
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-77
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-81
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-82
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-80
	iot-controller -->|!CVE-2022-35927 0,39| soc-smoke
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-85
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-86
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-83
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-84
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-89
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-87
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-88
	iot-controller -->|!CVE-2022-35927 0,39| soc-temperature
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-5
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-6
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-3
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-4
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-1
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-2
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-16
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-17
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-14
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-15
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-18
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-19
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-12
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-13
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-10
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-11
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-27
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-28
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-25
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-26
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-29
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-20
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-23
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-24
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-21
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-22
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-100
	iot-controller -->|!CVE-2022-35927 0,39| soc-motion
	iot-controller -->|!CVE-2022-35927 0,39| soc-humidity
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-58
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-59
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-52
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-53
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-50
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-51
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-56
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-57
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-54
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-55
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-60
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-69
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-63
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-64
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-61
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-62
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-67
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-68
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-65
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-66
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-38
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-39
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-36
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-37
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-30
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-31
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-34
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-35
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-32
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-33
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-49
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-47
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-48
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-41
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-42
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-40
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-45
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-46
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-43
	iot-controller -->|!CVE-2022-35927 0,39| soc-custom-44
	soc-temperature-software -->|!CVE-2022-35927 0,39| soc-temperature
	soc-custom-60 -->|hasFirewall 0,20| iot-controller
	soc-custom-60 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-60 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-60 -->|!CVE-2022-25666 0,08| soc-custom-60-software
	soc-custom-60 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-60 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-51-software -->|!CVE-2022-35927 0,39| soc-custom-51
	soc-custom-92-software -->|!CVE-2022-35927 0,39| soc-custom-92
	soc-custom-32-software -->|!CVE-2022-35927 0,39| soc-custom-32
	soc-custom-69 -->|hasFirewall 0,20| iot-controller
	soc-custom-69 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-69 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-69 -->|!CVE-2022-25666 0,08| soc-custom-69-software
	soc-custom-69 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-69 -->|!CVE-2022-35927 0,39| iot-controller
	router -->|!firewall-risk 0,80| cloud-printer
	router -->|!firewall-risk 0,80| cloud-weather
	router -->|!firewall-risk 0,80| printer
	router -->|!firewall-risk 0,80| cloud-notification
	router -->|hasFirewall 0,20| iot-controller
	router -->|!physically-secured-risk 0,80| cloud-printer
	router -->|!physically-secured-risk 0,80| cloud-weather
	router -->|!physically-secured-risk 0,80| printer
	router -->|!physically-secured-risk 0,80| cloud-notification
	router -->|isPhysicallySecured 0,20| iot-controller
	router -->|!software-encrypted-risk 0,80| cloud-printer
	router -->|!software-encrypted-risk 0,80| cloud-weather
	router -->|!software-encrypted-risk 0,80| printer
	router -->|!software-encrypted-risk 0,80| cloud-notification
	router -->|!software-encrypted-risk 0,80| iot-controller
	router -->|!CVE-2022-35927 0,39| printer
	router -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-63 -->|hasFirewall 0,20| iot-controller
	soc-custom-63 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-63 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-63 -->|!CVE-2022-25666 0,08| soc-custom-63-software
	soc-custom-63 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-63 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-79-software -->|!CVE-2022-35927 0,39| soc-custom-79
	soc-custom-64 -->|hasFirewall 0,20| iot-controller
	soc-custom-64 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-64 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-64 -->|!CVE-2022-25666 0,08| soc-custom-64-software
	soc-custom-64 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-64 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-61 -->|hasFirewall 0,20| iot-controller
	soc-custom-61 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-61 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-61 -->|!CVE-2022-25666 0,08| soc-custom-61-software
	soc-custom-61 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-61 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-62 -->|hasFirewall 0,20| iot-controller
	soc-custom-62 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-62 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-62 -->|!CVE-2022-25666 0,08| soc-custom-62-software
	soc-custom-62 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-62 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-67 -->|hasFirewall 0,20| iot-controller
	soc-custom-67 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-67 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-67 -->|!CVE-2022-25666 0,08| soc-custom-67-software
	soc-custom-67 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-67 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-68 -->|hasFirewall 0,20| iot-controller
	soc-custom-68 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-68 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-68 -->|!CVE-2022-25666 0,08| soc-custom-68-software
	soc-custom-68 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-68 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-65 -->|hasFirewall 0,20| iot-controller
	soc-custom-65 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-65 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-65 -->|!CVE-2022-25666 0,08| soc-custom-65-software
	soc-custom-65 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-65 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-66 -->|hasFirewall 0,20| iot-controller
	soc-custom-66 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-66 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-66 -->|!CVE-2022-25666 0,08| soc-custom-66-software
	soc-custom-66 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-66 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-38-software -->|!CVE-2022-35927 0,39| soc-custom-38
	soc-custom-82-software -->|!CVE-2022-35927 0,39| soc-custom-82
	soc-custom-73-software -->|!CVE-2022-35927 0,39| soc-custom-73
	soc-custom-38 -->|hasFirewall 0,20| iot-controller
	soc-custom-38 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-38 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-38 -->|!CVE-2022-25666 0,08| soc-custom-38-software
	soc-custom-38 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-38 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-39 -->|hasFirewall 0,20| iot-controller
	soc-custom-39 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-39 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-39 -->|!CVE-2022-25666 0,08| soc-custom-39-software
	soc-custom-39 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-39 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-36 -->|hasFirewall 0,20| iot-controller
	soc-custom-36 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-36 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-36 -->|!CVE-2022-25666 0,08| soc-custom-36-software
	soc-custom-36 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-36 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-37 -->|hasFirewall 0,20| iot-controller
	soc-custom-37 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-37 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-37 -->|!CVE-2022-25666 0,08| soc-custom-37-software
	soc-custom-37 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-37 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-48-software -->|!CVE-2022-35927 0,39| soc-custom-48
	soc-custom-54-software -->|!CVE-2022-35927 0,39| soc-custom-54
	soc-custom-30 -->|hasFirewall 0,20| iot-controller
	soc-custom-30 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-30 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-30 -->|!CVE-2022-25666 0,08| soc-custom-30-software
	soc-custom-30 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-30 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-31 -->|hasFirewall 0,20| iot-controller
	soc-custom-31 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-31 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-31 -->|!CVE-2022-25666 0,08| soc-custom-31-software
	soc-custom-31 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-31 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-34 -->|hasFirewall 0,20| iot-controller
	soc-custom-34 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-34 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-34 -->|!CVE-2022-25666 0,08| soc-custom-34-software
	soc-custom-34 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-34 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-57-software -->|!CVE-2022-35927 0,39| soc-custom-57
	soc-custom-35 -->|hasFirewall 0,20| iot-controller
	soc-custom-35 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-35 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-35 -->|!CVE-2022-25666 0,08| soc-custom-35-software
	soc-custom-35 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-35 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-32 -->|hasFirewall 0,20| iot-controller
	soc-custom-32 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-32 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-32 -->|!CVE-2022-25666 0,08| soc-custom-32-software
	soc-custom-32 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-32 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-33 -->|hasFirewall 0,20| iot-controller
	soc-custom-33 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-33 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-33 -->|!CVE-2022-25666 0,08| soc-custom-33-software
	soc-custom-33 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-33 -->|!CVE-2022-35927 0,39| iot-controller
	soc-door-lock -->|hasFirewall 0,20| iot-controller
	soc-door-lock -->|isPhysicallySecured 0,20| iot-controller
	soc-door-lock -->|!software-encrypted-risk 0,80| iot-controller
	soc-door-lock -->|!CVE-2022-25666 0,08| soc-door-lock-software
	soc-door-lock -->|!CVE-2022-25666 0,08| iot-controller
	soc-door-lock -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-95-software -->|!CVE-2022-35927 0,39| soc-custom-95
	soc-custom-60-software -->|!CVE-2022-35927 0,39| soc-custom-60
	soc-custom-49 -->|hasFirewall 0,20| iot-controller
	soc-custom-49 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-49 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-49 -->|!CVE-2022-25666 0,08| soc-custom-49-software
	soc-custom-49 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-49 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-35-software -->|!CVE-2022-35927 0,39| soc-custom-35
	soc-custom-47 -->|hasFirewall 0,20| iot-controller
	soc-custom-47 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-47 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-47 -->|!CVE-2022-25666 0,08| soc-custom-47-software
	soc-custom-47 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-47 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-48 -->|hasFirewall 0,20| iot-controller
	soc-custom-48 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-48 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-48 -->|!CVE-2022-25666 0,08| soc-custom-48-software
	soc-custom-48 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-48 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-41 -->|hasFirewall 0,20| iot-controller
	soc-custom-41 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-41 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-41 -->|!CVE-2022-25666 0,08| soc-custom-41-software
	soc-custom-41 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-41 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-42 -->|hasFirewall 0,20| iot-controller
	soc-custom-42 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-42 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-42 -->|!CVE-2022-25666 0,08| soc-custom-42-software
	soc-custom-42 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-42 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-76-software -->|!CVE-2022-35927 0,39| soc-custom-76
	printer-software -->|!CVE-2022-35927 0,39| printer
	soc-custom-29-software -->|!CVE-2022-35927 0,39| soc-custom-29
	soc-custom-40 -->|hasFirewall 0,20| iot-controller
	soc-custom-40 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-40 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-40 -->|!CVE-2022-25666 0,08| soc-custom-40-software
	soc-custom-40 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-40 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-45 -->|hasFirewall 0,20| iot-controller
	soc-custom-45 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-45 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-45 -->|!CVE-2022-25666 0,08| soc-custom-45-software
	soc-custom-45 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-45 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-46 -->|hasFirewall 0,20| iot-controller
	soc-custom-46 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-46 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-46 -->|!CVE-2022-25666 0,08| soc-custom-46-software
	soc-custom-46 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-46 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-43 -->|hasFirewall 0,20| iot-controller
	soc-custom-43 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-43 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-43 -->|!CVE-2022-25666 0,08| soc-custom-43-software
	soc-custom-43 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-43 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-44 -->|hasFirewall 0,20| iot-controller
	soc-custom-44 -->|isPhysicallySecured 0,20| iot-controller
	soc-custom-44 -->|!software-encrypted-risk 0,80| iot-controller
	soc-custom-44 -->|!CVE-2022-25666 0,08| soc-custom-44-software
	soc-custom-44 -->|!CVE-2022-25666 0,08| iot-controller
	soc-custom-44 -->|!CVE-2022-35927 0,39| iot-controller
	soc-custom-3-software -->|!CVE-2022-35927 0,39| soc-custom-3