%% 275000
flowchart LR
	soc-custom-59-software[soc-custom-59-software]
	soc-custom-9[soc-custom-9]
	soc-custom-92[soc-custom-92]
	soc-custom-93[soc-custom-93]
	soc-custom-7[soc-custom-7]
	soc-custom-90[soc-custom-90]
	soc-custom-8[soc-custom-8]
	soc-custom-91[soc-custom-91]
	soc-custom-77-software[soc-custom-77-software]
	soc-custom-16-software[soc-custom-16-software]
	soc-alarm[soc-alarm]
	soc-custom-96[soc-custom-96]
	soc-custom-97[soc-custom-97]
	soc-custom-94[soc-custom-94]
	soc-custom-95[soc-custom-95]
	soc-custom-34-software[soc-custom-34-software]
	soc-custom-98[soc-custom-98]
	soc-custom-90-software[soc-custom-90-software]
	soc-custom-99[soc-custom-99]
	soc-custom-5-software[soc-custom-5-software]
	soc-custom-26-software[soc-custom-26-software]
	soc-custom-49-software[soc-custom-49-software]
	soc-custom-67-software[soc-custom-67-software]
	desktop-software[desktop-software]
	soc-custom-80-software[soc-custom-80-software]
	soc-light[soc-light]
	soc-custom-44-software[soc-custom-44-software]
	soc-custom-62-software[soc-custom-62-software]
	soc-custom-85-software[soc-custom-85-software]
	soc-custom-70[soc-custom-70]
	cloud-printer[cloud-printer]
	soc-custom-71[soc-custom-71]
	soc-custom-97-software[soc-custom-97-software]
	soc-custom-39-software[soc-custom-39-software]
	soc-custom-70-software[soc-custom-70-software]
	soc-custom-42-software[soc-custom-42-software]
	soc-custom-36-software[soc-custom-36-software]
	cloud-notification-software[cloud-notification-software]
	soc-custom-74[soc-custom-74]
	soc-custom-75[soc-custom-75]
	soc-alarm-software[soc-alarm-software]
	soc-custom-72[soc-custom-72]
	soc-custom-73[soc-custom-73]
	soc-custom-78[soc-custom-78]
	soc-custom-7-software[soc-custom-7-software]
	soc-custom-79[soc-custom-79]
	soc-custom-76[soc-custom-76]
	soc-custom-77[soc-custom-77]
	soc-custom-75-software[soc-custom-75-software]
	soc-custom-72-software[soc-custom-72-software]
	soc-custom-81[soc-custom-81]
	soc-custom-82[soc-custom-82]
	soc-custom-69-software[soc-custom-69-software]
	soc-custom-80[soc-custom-80]
	soc-custom-2-software[soc-custom-2-software]
	soc-custom-64-software[soc-custom-64-software]
	soc-smoke[soc-smoke]
	soc-gate-software[soc-gate-software]
	soc-custom-85[soc-custom-85]
	soc-custom-47-software[soc-custom-47-software]
	soc-custom-86[soc-custom-86]
	soc-custom-100-software[soc-custom-100-software]
	soc-custom-83[soc-custom-83]
	soc-custom-84[soc-custom-84]
	soc-custom-89[soc-custom-89]
	soc-custom-87[soc-custom-87]
	soc-custom-88[soc-custom-88]
	soc-temperature[soc-temperature]
	soc-custom-56-software[soc-custom-56-software]
	soc-custom-65-software[soc-custom-65-software]
	soc-custom-28-software[soc-custom-28-software]
	soc-custom-93-software[soc-custom-93-software]
	soc-custom-84-software[soc-custom-84-software]
	soc-custom-40-software[soc-custom-40-software]
	soc-custom-14-software[soc-custom-14-software]
	soc-custom-37-software[soc-custom-37-software]
	soc-custom-55-software[soc-custom-55-software]
	soc-custom-74-software[soc-custom-74-software]
	soc-smoke-software[soc-smoke-software]
	soc-custom-21-software[soc-custom-21-software]
	soc-custom-27-software[soc-custom-27-software]
	soc-custom-33-software[soc-custom-33-software]
	soc-custom-24-software[soc-custom-24-software]
	soc-custom-18-software[soc-custom-18-software]
	soc-custom-1-software[soc-custom-1-software]
	soc-door-lock-software[soc-door-lock-software]
	soc-custom-52-software[soc-custom-52-software]
	soc-custom-11-software[soc-custom-11-software]
	soc-motion-software[soc-motion-software]
	soc-custom-46-software[soc-custom-46-software]
	soc-gate[soc-gate]
	cloud-weather[cloud-weather]
	soc-custom-8-software[soc-custom-8-software]
	soc-custom-87-software[soc-custom-87-software]
	desktop[desktop]
	server-software[server-software]
	soc-custom-5[soc-custom-5]
	soc-custom-6[soc-custom-6]
	soc-custom-3[soc-custom-3]
	soc-custom-4[soc-custom-4]
	soc-custom-71-software[soc-custom-71-software]
	soc-custom-1[soc-custom-1]
	soc-custom-30-software[soc-custom-30-software]
	soc-custom-2[soc-custom-2]
	printer[printer]
	soc-custom-10-software[soc-custom-10-software]
	soc-custom-68-software[soc-custom-68-software]
	soc-custom-16[soc-custom-16]
	soc-custom-96-software[soc-custom-96-software]
	soc-custom-17[soc-custom-17]
	soc-custom-14[soc-custom-14]
	soc-custom-15[soc-custom-15]
	soc-custom-86-software[soc-custom-86-software]
	soc-custom-18[soc-custom-18]
	soc-custom-19[soc-custom-19]
	soc-custom-81-software[soc-custom-81-software]
	soc-custom-12[soc-custom-12]
	soc-custom-25-software[soc-custom-25-software]
	soc-custom-13[soc-custom-13]
	soc-custom-10[soc-custom-10]
	soc-custom-11[soc-custom-11]
	soc-custom-43-software[soc-custom-43-software]
	soc-custom-63-software[soc-custom-63-software]
	soc-custom-78-software[soc-custom-78-software]
	soc-custom-20-software[soc-custom-20-software]
	soc-custom-27[soc-custom-27]
	soc-custom-28[soc-custom-28]
	soc-custom-25[soc-custom-25]
	soc-custom-26[soc-custom-26]
	database[database]
	soc-custom-29[soc-custom-29]
	soc-custom-6-software[soc-custom-6-software]
	soc-custom-15-software[soc-custom-15-software]
	soc-custom-20[soc-custom-20]
	soc-custom-23[soc-custom-23]
	soc-custom-24[soc-custom-24]
	soc-custom-21[soc-custom-21]
	soc-custom-22[soc-custom-22]
	soc-custom-88-software[soc-custom-88-software]
	soc-custom-100[soc-custom-100]
	soc-custom-91-software[soc-custom-91-software]
	soc-custom-4-software[soc-custom-4-software]
	soc-custom-61-software[soc-custom-61-software]
	soc-motion[soc-motion]
	soc-humidity-software[soc-humidity-software]
	soc-custom-45-software[soc-custom-45-software]
	soc-humidity[soc-humidity]
	soc-custom-66-software[soc-custom-66-software]
	server[server]
	cloud-notification[cloud-notification]
	soc-custom-17-software[soc-custom-17-software]
	soc-custom-58-software[soc-custom-58-software]
	soc-custom-83-software[soc-custom-83-software]
	soc-light-software[soc-light-software]
	soc-custom-23-software[soc-custom-23-software]
	soc-custom-99-software[soc-custom-99-software]
	soc-custom-9-software[soc-custom-9-software]
	soc-custom-12-software[soc-custom-12-software]
	soc-custom-94-software[soc-custom-94-software]
	soc-custom-53-software[soc-custom-53-software]
	soc-custom-50-software[soc-custom-50-software]
	soc-custom-41-software[soc-custom-41-software]
	soc-custom-58[soc-custom-58]
	soc-custom-19-software[soc-custom-19-software]
	soc-custom-59[soc-custom-59]
	soc-custom-89-software[soc-custom-89-software]
	soc-custom-13-software[soc-custom-13-software]
	soc-custom-22-software[soc-custom-22-software]
	soc-custom-52[soc-custom-52]
	soc-custom-53[soc-custom-53]
	soc-custom-50[soc-custom-50]
	iot-controller-software[iot-controller-software]
	soc-custom-31-software[soc-custom-31-software]
	soc-custom-51[soc-custom-51]
	soc-custom-56[soc-custom-56]
	soc-custom-57[soc-custom-57]
	soc-custom-98-software[soc-custom-98-software]
	soc-custom-54[soc-custom-54]
	soc-custom-55[soc-custom-55]
	iot-controller[iot-controller]
	soc-temperature-software[soc-temperature-software]
	soc-custom-60[soc-custom-60]
	soc-custom-51-software[soc-custom-51-software]
	soc-custom-92-software[soc-custom-92-software]
	soc-custom-32-software[soc-custom-32-software]
	soc-custom-69[soc-custom-69]
	router[router]
	cloud-printer-software[cloud-printer-software]
	soc-custom-63[soc-custom-63]
	soc-custom-79-software[soc-custom-79-software]
	soc-custom-64[soc-custom-64]
	cloud-weather-software[cloud-weather-software]
	soc-custom-61[soc-custom-61]
	soc-custom-62[soc-custom-62]
	soc-custom-67[soc-custom-67]
	soc-custom-68[soc-custom-68]
	soc-custom-65[soc-custom-65]
	soc-custom-66[soc-custom-66]
	soc-custom-38-software[soc-custom-38-software]
	soc-custom-82-software[soc-custom-82-software]
	soc-custom-73-software[soc-custom-73-software]
	soc-custom-38[soc-custom-38]
	soc-custom-39[soc-custom-39]
	soc-custom-36[soc-custom-36]
	soc-custom-37[soc-custom-37]
	soc-custom-48-software[soc-custom-48-software]
	soc-custom-54-software[soc-custom-54-software]
	soc-custom-30[soc-custom-30]
	soc-custom-31[soc-custom-31]
	soc-custom-34[soc-custom-34]
	soc-custom-57-software[soc-custom-57-software]
	soc-custom-35[soc-custom-35]
	soc-custom-32[soc-custom-32]
	soc-custom-33[soc-custom-33]
	soc-door-lock[soc-door-lock]
	soc-custom-95-software[soc-custom-95-software]
	soc-custom-60-software[soc-custom-60-software]
	soc-custom-49[soc-custom-49]
	soc-custom-35-software[soc-custom-35-software]
	soc-custom-47[soc-custom-47]
	soc-custom-48[soc-custom-48]
	soc-custom-41[soc-custom-41]
	soc-custom-42[soc-custom-42]
	soc-custom-76-software[soc-custom-76-software]
	printer-software[printer-software]
	soc-custom-29-software[soc-custom-29-software]
	soc-custom-40[soc-custom-40]
	soc-custom-45[soc-custom-45]
	soc-custom-46[soc-custom-46]
	soc-custom-43[soc-custom-43]
	soc-custom-44[soc-custom-44]
	soc-custom-3-software[soc-custom-3-software]
	soc-custom-59-software --> soc-custom-59
	soc-custom-59-software --> database
	soc-custom-9 --> soc-custom-9-software
	soc-custom-9 --> iot-controller
	soc-custom-92 --> soc-custom-92-software
	soc-custom-92 --> iot-controller
	soc-custom-93 --> soc-custom-93-software
	soc-custom-93 --> iot-controller
	soc-custom-7 --> soc-custom-7-software
	soc-custom-7 --> iot-controller
	soc-custom-90 --> soc-custom-90-software
	soc-custom-90 --> iot-controller
	soc-custom-8 --> soc-custom-8-software
	soc-custom-8 --> iot-controller
	soc-custom-91 --> soc-custom-91-software
	soc-custom-91 --> iot-controller
	soc-custom-77-software --> soc-custom-77
	soc-custom-77-software --> database
	soc-custom-16-software --> soc-custom-16
	soc-custom-16-software --> database
	soc-alarm --> soc-alarm-software
	soc-alarm --> iot-controller
	soc-custom-96 --> soc-custom-96-software
	soc-custom-96 --> iot-controller
	soc-custom-97 --> soc-custom-97-software
	soc-custom-97 --> iot-controller
	soc-custom-94 --> soc-custom-94-software
	soc-custom-94 --> iot-controller
	soc-custom-95 --> soc-custom-95-software
	soc-custom-95 --> iot-controller
	soc-custom-34-software --> soc-custom-34
	soc-custom-34-software --> database
	soc-custom-98 --> soc-custom-98-software
	soc-custom-98 --> iot-controller
	soc-custom-90-software --> soc-custom-90
	soc-custom-90-software --> database
	soc-custom-99 --> soc-custom-99-software
	soc-custom-99 --> iot-controller
	soc-custom-5-software --> soc-custom-5
	soc-custom-5-software --> database
	soc-custom-26-software --> soc-custom-26
	soc-custom-26-software --> database
	soc-custom-49-software --> soc-custom-49
	soc-custom-49-software --> database
	soc-custom-67-software --> soc-custom-67
	soc-custom-67-software --> database
	desktop-software --> desktop
	soc-custom-80-software --> soc-custom-80
	soc-custom-80-software --> database
	soc-light --> soc-light-software
	soc-light --> iot-controller
	soc-custom-44-software --> soc-custom-44
	soc-custom-44-software --> database
	soc-custom-62-software --> soc-custom-62
	soc-custom-62-software --> database
	soc-custom-85-software --> soc-custom-85
	soc-custom-85-software --> database
	soc-custom-70 --> soc-custom-70-software
	soc-custom-70 --> iot-controller
	cloud-printer --> cloud-printer-software
	cloud-printer --> router
	soc-custom-71 --> soc-custom-71-software
	soc-custom-71 --> iot-controller
	soc-custom-97-software --> soc-custom-97
	soc-custom-97-software --> database
	soc-custom-39-software --> soc-custom-39
	soc-custom-39-software --> database
	soc-custom-70-software --> soc-custom-70
	soc-custom-70-software --> database
	soc-custom-42-software --> soc-custom-42
	soc-custom-42-software --> database
	soc-custom-36-software --> soc-custom-36
	soc-custom-36-software --> database
	cloud-notification-software --> cloud-notification
	cloud-notification-software --> iot-controller-software
	soc-custom-74 --> soc-custom-74-software
	soc-custom-74 --> iot-controller
	soc-custom-75 --> soc-custom-75-software
	soc-custom-75 --> iot-controller
	soc-alarm-software --> soc-alarm
	soc-alarm-software --> database
	soc-custom-72 --> soc-custom-72-software
	soc-custom-72 --> iot-controller
	soc-custom-73 --> soc-custom-73-software
	soc-custom-73 --> iot-controller
	soc-custom-78 --> soc-custom-78-software
	soc-custom-78 --> iot-controller
	soc-custom-7-software --> soc-custom-7
	soc-custom-7-software --> database
	soc-custom-79 --> soc-custom-79-software
	soc-custom-79 --> iot-controller
	soc-custom-76 --> soc-custom-76-software
	soc-custom-76 --> iot-controller
	soc-custom-77 --> soc-custom-77-software
	soc-custom-77 --> iot-controller
	soc-custom-75-software --> soc-custom-75
	soc-custom-75-software --> database
	soc-custom-72-software --> soc-custom-72
	soc-custom-72-software --> database
	soc-custom-81 --> soc-custom-81-software
	soc-custom-81 --> iot-controller
	soc-custom-82 --> soc-custom-82-software
	soc-custom-82 --> iot-controller
	soc-custom-69-software --> soc-custom-69
	soc-custom-69-software --> database
	soc-custom-80 --> soc-custom-80-software
	soc-custom-80 --> iot-controller
	soc-custom-2-software --> soc-custom-2
	soc-custom-2-software --> database
	soc-custom-64-software --> soc-custom-64
	soc-custom-64-software --> database
	soc-smoke --> soc-smoke-software
	soc-smoke --> iot-controller
	soc-gate-software --> soc-gate
	soc-gate-software --> database
	soc-custom-85 --> soc-custom-85-software
	soc-custom-85 --> iot-controller
	soc-custom-47-software --> soc-custom-47
	soc-custom-47-software --> database
	soc-custom-86 --> soc-custom-86-software
	soc-custom-86 --> iot-controller
	soc-custom-100-software --> soc-custom-100
	soc-custom-100-software --> database
	soc-custom-83 --> soc-custom-83-software
	soc-custom-83 --> iot-controller
	soc-custom-84 --> soc-custom-84-software
	soc-custom-84 --> iot-controller
	soc-custom-89 --> soc-custom-89-software
	soc-custom-89 --> iot-controller
	soc-custom-87 --> soc-custom-87-software
	soc-custom-87 --> iot-controller
	soc-custom-88 --> soc-custom-88-software
	soc-custom-88 --> iot-controller
	soc-temperature --> soc-temperature-software
	soc-temperature --> iot-controller
	soc-custom-56-software --> soc-custom-56
	soc-custom-56-software --> database
	soc-custom-65-software --> soc-custom-65
	soc-custom-65-software --> database
	soc-custom-28-software --> soc-custom-28
	soc-custom-28-software --> database
	soc-custom-93-software --> soc-custom-93
	soc-custom-93-software --> database
	soc-custom-84-software --> soc-custom-84
	soc-custom-84-software --> database
	soc-custom-40-software --> soc-custom-40
	soc-custom-40-software --> database
	soc-custom-14-software --> soc-custom-14
	soc-custom-14-software --> database
	soc-custom-37-software --> soc-custom-37
	soc-custom-37-software --> database
	soc-custom-55-software --> soc-custom-55
	soc-custom-55-software --> database
	soc-custom-74-software --> soc-custom-74
	soc-custom-74-software --> database
	soc-smoke-software --> soc-smoke
	soc-smoke-software --> database
	soc-custom-21-software --> soc-custom-21
	soc-custom-21-software --> database
	soc-custom-27-software --> soc-custom-27
	soc-custom-27-software --> database
	soc-custom-33-software --> soc-custom-33
	soc-custom-33-software --> database
	soc-custom-24-software --> soc-custom-24
	soc-custom-24-software --> database
	soc-custom-18-software --> soc-custom-18
	soc-custom-18-software --> database
	soc-custom-1-software --> soc-custom-1
	soc-custom-1-software --> database
	soc-door-lock-software --> soc-door-lock
	soc-door-lock-software --> database
	soc-custom-52-software --> soc-custom-52
	soc-custom-52-software --> database
	soc-custom-11-software --> soc-custom-11
	soc-custom-11-software --> database
	soc-motion-software --> soc-motion
	soc-motion-software --> database
	soc-custom-46-software --> soc-custom-46
	soc-custom-46-software --> database
	soc-gate --> soc-gate-software
	soc-gate --> iot-controller
	cloud-weather --> cloud-weather-software
	cloud-weather --> router
	soc-custom-8-software --> soc-custom-8
	soc-custom-8-software --> database
	soc-custom-87-software --> soc-custom-87
	soc-custom-87-software --> database
	desktop --> desktop-software
	desktop --> iot-controller
	server-software --> server
	server-software --> database
	soc-custom-5 --> soc-custom-5-software
	soc-custom-5 --> iot-controller
	soc-custom-6 --> soc-custom-6-software
	soc-custom-6 --> iot-controller
	soc-custom-3 --> soc-custom-3-software
	soc-custom-3 --> iot-controller
	soc-custom-4 --> soc-custom-4-software
	soc-custom-4 --> iot-controller
	soc-custom-71-software --> soc-custom-71
	soc-custom-71-software --> database
	soc-custom-1 --> soc-custom-1-software
	soc-custom-1 --> iot-controller
	soc-custom-30-software --> soc-custom-30
	soc-custom-30-software --> database
	soc-custom-2 --> soc-custom-2-software
	soc-custom-2 --> iot-controller
	printer --> printer-software
	printer --> router
	soc-custom-10-software --> soc-custom-10
	soc-custom-10-software --> database
	soc-custom-68-software --> soc-custom-68
	soc-custom-68-software --> database
	soc-custom-16 --> soc-custom-16-software
	soc-custom-16 --> iot-controller
	soc-custom-96-software --> soc-custom-96
	soc-custom-96-software --> database
	soc-custom-17 --> soc-custom-17-software
	soc-custom-17 --> iot-controller
	soc-custom-14 --> soc-custom-14-software
	soc-custom-14 --> iot-controller
	soc-custom-15 --> soc-custom-15-software
	soc-custom-15 --> iot-controller
	soc-custom-86-software --> soc-custom-86
	soc-custom-86-software --> database
	soc-custom-18 --> soc-custom-18-software
	soc-custom-18 --> iot-controller
	soc-custom-19 --> soc-custom-19-software
	soc-custom-19 --> iot-controller
	soc-custom-81-software --> soc-custom-81
	soc-custom-81-software --> database
	soc-custom-12 --> soc-custom-12-software
	soc-custom-12 --> iot-controller
	soc-custom-25-software --> soc-custom-25
	soc-custom-25-software --> database
	soc-custom-13 --> soc-custom-13-software
	soc-custom-13 --> iot-controller
	soc-custom-10 --> soc-custom-10-software
	soc-custom-10 --> iot-controller
	soc-custom-11 --> soc-custom-11-software
	soc-custom-11 --> iot-controller
	soc-custom-43-software --> soc-custom-43
	soc-custom-43-software --> database
	soc-custom-63-software --> soc-custom-63
	soc-custom-63-software --> database
	soc-custom-78-software --> soc-custom-78
	soc-custom-78-software --> database
	soc-custom-20-software --> soc-custom-20
	soc-custom-20-software --> database
	soc-custom-27 --> soc-custom-27-software
	soc-custom-27 --> iot-controller
	soc-custom-28 --> soc-custom-28-software
	soc-custom-28 --> iot-controller
	soc-custom-25 --> soc-custom-25-software
	soc-custom-25 --> iot-controller
	soc-custom-26 --> soc-custom-26-software
	soc-custom-26 --> iot-controller
	database --> iot-controller
	database --> iot-controller-software
	database --> soc-motion-software
	database --> soc-humidity-software
	database --> soc-door-lock-software
	database --> soc-gate-software
	database --> soc-alarm-software
	database --> soc-smoke-software
	database --> soc-temperature-software
	database --> soc-light-software
	database --> server-software
	database --> soc-custom-1-software
	database --> soc-custom-2-software
	database --> soc-custom-3-software
	database --> soc-custom-4-software
	database --> soc-custom-5-software
	database --> soc-custom-6-software
	database --> soc-custom-7-software
	database --> soc-custom-8-software
	database --> soc-custom-9-software
	database --> soc-custom-10-software
	database --> soc-custom-11-software
	database --> soc-custom-12-software
	database --> soc-custom-13-software
	database --> soc-custom-14-software
	database --> soc-custom-15-software
	database --> soc-custom-16-software
	database --> soc-custom-17-software
	database --> soc-custom-18-software
	database --> soc-custom-19-software
	database --> soc-custom-20-software
	database --> soc-custom-21-software
	database --> soc-custom-22-software
	database --> soc-custom-23-software
	database --> soc-custom-24-software
	database --> soc-custom-25-software
	database --> soc-custom-26-software
	database --> soc-custom-27-software
	database --> soc-custom-28-software
	database --> soc-custom-29-software
	database --> soc-custom-30-software
	database --> soc-custom-31-software
	database --> soc-custom-32-software
	database --> soc-custom-33-software
	database --> soc-custom-34-software
	database --> soc-custom-35-software
	database --> soc-custom-36-software
	database --> soc-custom-37-software
	database --> soc-custom-38-software
	database --> soc-custom-39-software
	database --> soc-custom-40-software
	database --> soc-custom-41-software
	database --> soc-custom-42-software
	database --> soc-custom-43-software
	database --> soc-custom-44-software
	database --> soc-custom-45-software
	database --> soc-custom-46-software
	database --> soc-custom-47-software
	database --> soc-custom-48-software
	database --> soc-custom-49-software
	database --> soc-custom-50-software
	database --> soc-custom-51-software
	database --> soc-custom-52-software
	database --> soc-custom-53-software
	database --> soc-custom-54-software
	database --> soc-custom-55-software
	database --> soc-custom-56-software
	database --> soc-custom-57-software
	database --> soc-custom-58-software
	database --> soc-custom-59-software
	database --> soc-custom-60-software
	database --> soc-custom-61-software
	database --> soc-custom-62-software
	database --> soc-custom-63-software
	database --> soc-custom-64-software
	database --> soc-custom-65-software
	database --> soc-custom-66-software
	database --> soc-custom-67-software
	database --> soc-custom-68-software
	database --> soc-custom-69-software
	database --> soc-custom-70-software
	database --> soc-custom-71-software
	database --> soc-custom-72-software
	database --> soc-custom-73-software
	database --> soc-custom-74-software
	database --> soc-custom-75-software
	database --> soc-custom-76-software
	database --> soc-custom-77-software
	database --> soc-custom-78-software
	database --> soc-custom-79-software
	database --> soc-custom-80-software
	database --> soc-custom-81-software
	database --> soc-custom-82-software
	database --> soc-custom-83-software
	database --> soc-custom-84-software
	database --> soc-custom-85-software
	database --> soc-custom-86-software
	database --> soc-custom-87-software
	database --> soc-custom-88-software
	database --> soc-custom-89-software
	database --> soc-custom-90-software
	database --> soc-custom-91-software
	database --> soc-custom-92-software
	database --> soc-custom-93-software
	database --> soc-custom-94-software
	database --> soc-custom-95-software
	database --> soc-custom-96-software
	database --> soc-custom-97-software
	database --> soc-custom-98-software
	database --> soc-custom-99-software
	database --> soc-custom-100-software
	soc-custom-29 --> soc-custom-29-software
	soc-custom-29 --> iot-controller
	soc-custom-6-software --> soc-custom-6
	soc-custom-6-software --> database
	soc-custom-15-software --> soc-custom-15
	soc-custom-15-software --> database
	soc-custom-20 --> soc-custom-20-software
	soc-custom-20 --> iot-controller
	soc-custom-23 --> soc-custom-23-software
	soc-custom-23 --> iot-controller
	soc-custom-24 --> soc-custom-24-software
	soc-custom-24 --> iot-controller
	soc-custom-21 --> soc-custom-21-software
	soc-custom-21 --> iot-controller
	soc-custom-22 --> soc-custom-22-software
	soc-custom-22 --> iot-controller
	soc-custom-88-software --> soc-custom-88
	soc-custom-88-software --> database
	soc-custom-100 --> soc-custom-100-software
	soc-custom-100 --> iot-controller
	soc-custom-91-software --> soc-custom-91
	soc-custom-91-software --> database
	soc-custom-4-software --> soc-custom-4
	soc-custom-4-software --> database
	soc-custom-61-software --> soc-custom-61
	soc-custom-61-software --> database
	soc-motion --> soc-motion-software
	soc-motion --> iot-controller
	soc-humidity-software --> soc-humidity
	soc-humidity-software --> database
	soc-custom-45-software --> soc-custom-45
	soc-custom-45-software --> database
	soc-humidity --> soc-humidity-software
	soc-humidity --> iot-controller
	soc-custom-66-software --> soc-custom-66
	soc-custom-66-software --> database
	server --> server-software
	cloud-notification --> cloud-notification-software
	cloud-notification --> router
	soc-custom-17-software --> soc-custom-17
	soc-custom-17-software --> database
	soc-custom-58-software --> soc-custom-58
	soc-custom-58-software --> database
	soc-custom-83-software --> soc-custom-83
	soc-custom-83-software --> database
	soc-light-software --> soc-light
	soc-light-software --> database
	soc-custom-23-software --> soc-custom-23
	soc-custom-23-software --> database
	soc-custom-99-software --> soc-custom-99
	soc-custom-99-software --> database
	soc-custom-9-software --> soc-custom-9
	soc-custom-9-software --> database
	soc-custom-12-software --> soc-custom-12
	soc-custom-12-software --> database
	soc-custom-94-software --> soc-custom-94
	soc-custom-94-software --> database
	soc-custom-53-software --> soc-custom-53
	soc-custom-53-software --> database
	soc-custom-50-software --> soc-custom-50
	soc-custom-50-software --> database
	soc-custom-41-software --> soc-custom-41
	soc-custom-41-software --> database
	soc-custom-58 --> soc-custom-58-software
	soc-custom-58 --> iot-controller
	soc-custom-19-software --> soc-custom-19
	soc-custom-19-software --> database
	soc-custom-59 --> soc-custom-59-software
	soc-custom-59 --> iot-controller
	soc-custom-89-software --> soc-custom-89
	soc-custom-89-software --> database
	soc-custom-13-software --> soc-custom-13
	soc-custom-13-software --> database
	soc-custom-22-software --> soc-custom-22
	soc-custom-22-software --> database
	soc-custom-52 --> soc-custom-52-software
	soc-custom-52 --> iot-controller
	soc-custom-53 --> soc-custom-53-software
	soc-custom-53 --> iot-controller
	soc-custom-50 --> soc-custom-50-software
	soc-custom-50 --> iot-controller
	iot-controller-software --> iot-controller
	iot-controller-software --> database
	iot-controller-software --> cloud-weather-software
	iot-controller-software --> cloud-notification-software
	soc-custom-31-software --> soc-custom-31
	soc-custom-31-software --> database
	soc-custom-51 --> soc-custom-51-software
	soc-custom-51 --> iot-controller
	soc-custom-56 --> soc-custom-56-software
	soc-custom-56 --> iot-controller
	soc-custom-57 --> soc-custom-57-software
	soc-custom-57 --> iot-controller
	soc-custom-98-software --> soc-custom-98
	soc-custom-98-software --> database
	soc-custom-54 --> soc-custom-54-software
	soc-custom-54 --> iot-controller
	soc-custom-55 --> soc-custom-55-software
	soc-custom-55 --> iot-controller
	iot-controller --> iot-controller-software
	iot-controller --> database
	iot-controller --> soc-motion
	iot-controller --> soc-humidity
	iot-controller --> soc-door-lock
	iot-controller --> soc-gate
	iot-controller --> soc-alarm
	iot-controller --> soc-smoke
	iot-controller --> soc-temperature
	iot-controller --> soc-light
	iot-controller --> router
	iot-controller --> desktop
	iot-controller --> soc-custom-1
	iot-controller --> soc-custom-2
	iot-controller --> soc-custom-3
	iot-controller --> soc-custom-4
	iot-controller --> soc-custom-5
	iot-controller --> soc-custom-6
	iot-controller --> soc-custom-7
	iot-controller --> soc-custom-8
	iot-controller --> soc-custom-9
	iot-controller --> soc-custom-10
	iot-controller --> soc-custom-11
	iot-controller --> soc-custom-12
	iot-controller --> soc-custom-13
	iot-controller --> soc-custom-14
	iot-controller --> soc-custom-15
	iot-controller --> soc-custom-16
	iot-controller --> soc-custom-17
	iot-controller --> soc-custom-18
	iot-controller --> soc-custom-19
	iot-controller --> soc-custom-20
	iot-controller --> soc-custom-21
	iot-controller --> soc-custom-22
	iot-controller --> soc-custom-23
	iot-controller --> soc-custom-24
	iot-controller --> soc-custom-25
	iot-controller --> soc-custom-26
	iot-controller --> soc-custom-27
	iot-controller --> soc-custom-28
	iot-controller --> soc-custom-29
	iot-controller --> soc-custom-30
	iot-controller --> soc-custom-31
	iot-controller --> soc-custom-32
	iot-controller --> soc-custom-33
	iot-controller --> soc-custom-34
	iot-controller --> soc-custom-35
	iot-controller --> soc-custom-36
	iot-controller --> soc-custom-37
	iot-controller --> soc-custom-38
	iot-controller --> soc-custom-39
	iot-controller --> soc-custom-40
	iot-controller --> soc-custom-41
	iot-controller --> soc-custom-42
	iot-controller --> soc-custom-43
	iot-controller --> soc-custom-44
	iot-controller --> soc-custom-45
	iot-controller --> soc-custom-46
	iot-controller --> soc-custom-47
	iot-controller --> soc-custom-48
	iot-controller --> soc-custom-49
	iot-controller --> soc-custom-50
	iot-controller --> soc-custom-51
	iot-controller --> soc-custom-52
	iot-controller --> soc-custom-53
	iot-controller --> soc-custom-54
	iot-controller --> soc-custom-55
	iot-controller --> soc-custom-56
	iot-controller --> soc-custom-57
	iot-controller --> soc-custom-58
	iot-controller --> soc-custom-59
	iot-controller --> soc-custom-60
	iot-controller --> soc-custom-61
	iot-controller --> soc-custom-62
	iot-controller --> soc-custom-63
	iot-controller --> soc-custom-64
	iot-controller --> soc-custom-65
	iot-controller --> soc-custom-66
	iot-controller --> soc-custom-67
	iot-controller --> soc-custom-68
	iot-controller --> soc-custom-69
	iot-controller --> soc-custom-70
	iot-controller --> soc-custom-71
	iot-controller --> soc-custom-72
	iot-controller --> soc-custom-73
	iot-controller --> soc-custom-74
	iot-controller --> soc-custom-75
	iot-controller --> soc-custom-76
	iot-controller --> soc-custom-77
	iot-controller --> soc-custom-78
	iot-controller --> soc-custom-79
	iot-controller --> soc-custom-80
	iot-controller --> soc-custom-81
	iot-controller --> soc-custom-82
	iot-controller --> soc-custom-83
	iot-controller --> soc-custom-84
	iot-controller --> soc-custom-85
	iot-controller --> soc-custom-86
	iot-controller --> soc-custom-87
	iot-controller --> soc-custom-88
	iot-controller --> soc-custom-89
	iot-controller --> soc-custom-90
	iot-controller --> soc-custom-91
	iot-controller --> soc-custom-92
	iot-controller --> soc-custom-93
	iot-controller --> soc-custom-94
	iot-controller --> soc-custom-95
	iot-controller --> soc-custom-96
	iot-controller --> soc-custom-97
	iot-controller --> soc-custom-98
	iot-controller --> soc-custom-99
	iot-controller --> soc-custom-100
	soc-temperature-software --> soc-temperature
	soc-temperature-software --> database
	soc-custom-60 --> soc-custom-60-software
	soc-custom-60 --> iot-controller
	soc-custom-51-software --> soc-custom-51
	soc-custom-51-software --> database
	soc-custom-92-software --> soc-custom-92
	soc-custom-92-software --> database
	soc-custom-32-software --> soc-custom-32
	soc-custom-32-software --> database
	soc-custom-69 --> soc-custom-69-software
	soc-custom-69 --> iot-controller
	router --> iot-controller
	router --> printer
	router --> cloud-printer
	router --> cloud-weather
	router --> cloud-notification
	cloud-printer-software --> cloud-printer
	cloud-printer-software --> printer-software
	soc-custom-63 --> soc-custom-63-software
	soc-custom-63 --> iot-controller
	soc-custom-79-software --> soc-custom-79
	soc-custom-79-software --> database
	soc-custom-64 --> soc-custom-64-software
	soc-custom-64 --> iot-controller
	cloud-weather-software --> cloud-weather
	cloud-weather-software --> iot-controller-software
	soc-custom-61 --> soc-custom-61-software
	soc-custom-61 --> iot-controller
	soc-custom-62 --> soc-custom-62-software
	soc-custom-62 --> iot-controller
	soc-custom-67 --> soc-custom-67-software
	soc-custom-67 --> iot-controller
	soc-custom-68 --> soc-custom-68-software
	soc-custom-68 --> iot-controller
	soc-custom-65 --> soc-custom-65-software
	soc-custom-65 --> iot-controller
	soc-custom-66 --> soc-custom-66-software
	soc-custom-66 --> iot-controller
	soc-custom-38-software --> soc-custom-38
	soc-custom-38-software --> database
	soc-custom-82-software --> soc-custom-82
	soc-custom-82-software --> database
	soc-custom-73-software --> soc-custom-73
	soc-custom-73-software --> database
	soc-custom-38 --> soc-custom-38-software
	soc-custom-38 --> iot-controller
	soc-custom-39 --> soc-custom-39-software
	soc-custom-39 --> iot-controller
	soc-custom-36 --> soc-custom-36-software
	soc-custom-36 --> iot-controller
	soc-custom-37 --> soc-custom-37-software
	soc-custom-37 --> iot-controller
	soc-custom-48-software --> soc-custom-48
	soc-custom-48-software --> database
	soc-custom-54-software --> soc-custom-54
	soc-custom-54-software --> database
	soc-custom-30 --> soc-custom-30-software
	soc-custom-30 --> iot-controller
	soc-custom-31 --> soc-custom-31-software
	soc-custom-31 --> iot-controller
	soc-custom-34 --> soc-custom-34-software
	soc-custom-34 --> iot-controller
	soc-custom-57-software --> soc-custom-57
	soc-custom-57-software --> database
	soc-custom-35 --> soc-custom-35-software
	soc-custom-35 --> iot-controller
	soc-custom-32 --> soc-custom-32-software
	soc-custom-32 --> iot-controller
	soc-custom-33 --> soc-custom-33-software
	soc-custom-33 --> iot-controller
	soc-door-lock --> soc-door-lock-software
	soc-door-lock --> iot-controller
	soc-custom-95-software --> soc-custom-95
	soc-custom-95-software --> database
	soc-custom-60-software --> soc-custom-60
	soc-custom-60-software --> database
	soc-custom-49 --> soc-custom-49-software
	soc-custom-49 --> iot-controller
	soc-custom-35-software --> soc-custom-35
	soc-custom-35-software --> database
	soc-custom-47 --> soc-custom-47-software
	soc-custom-47 --> iot-controller
	soc-custom-48 --> soc-custom-48-software
	soc-custom-48 --> iot-controller
	soc-custom-41 --> soc-custom-41-software
	soc-custom-41 --> iot-controller
	soc-custom-42 --> soc-custom-42-software
	soc-custom-42 --> iot-controller
	soc-custom-76-software --> soc-custom-76
	soc-custom-76-software --> database
	printer-software --> printer
	printer-software --> cloud-printer-software
	soc-custom-29-software --> soc-custom-29
	soc-custom-29-software --> database
	soc-custom-40 --> soc-custom-40-software
	soc-custom-40 --> iot-controller
	soc-custom-45 --> soc-custom-45-software
	soc-custom-45 --> iot-controller
	soc-custom-46 --> soc-custom-46-software
	soc-custom-46 --> iot-controller
	soc-custom-43 --> soc-custom-43-software
	soc-custom-43 --> iot-controller
	soc-custom-44 --> soc-custom-44-software
	soc-custom-44 --> iot-controller
	soc-custom-3-software --> soc-custom-3
	soc-custom-3-software --> database