%% 250000
flowchart LR
	printer[printer]
	soc-custom-9[soc-custom-9]
	soc-custom-7[soc-custom-7]
	soc-custom-8[soc-custom-8]
	soc-custom-10-software[soc-custom-10-software]
	soc-custom-16[soc-custom-16]
	soc-custom-17[soc-custom-17]
	soc-custom-14[soc-custom-14]
	soc-custom-15[soc-custom-15]
	soc-custom-16-software[soc-custom-16-software]
	soc-alarm[soc-alarm]
	soc-custom-18[soc-custom-18]
	soc-custom-19[soc-custom-19]
	soc-custom-12[soc-custom-12]
	soc-custom-25-software[soc-custom-25-software]
	soc-custom-13[soc-custom-13]
	soc-custom-34-software[soc-custom-34-software]
	soc-custom-10[soc-custom-10]
	soc-custom-11[soc-custom-11]
	soc-custom-43-software[soc-custom-43-software]
	soc-custom-5-software[soc-custom-5-software]
	soc-custom-20-software[soc-custom-20-software]
	soc-custom-26-software[soc-custom-26-software]
	soc-custom-49-software[soc-custom-49-software]
	soc-custom-27[soc-custom-27]
	soc-custom-28[soc-custom-28]
	soc-custom-25[soc-custom-25]
	desktop-software[desktop-software]
	soc-custom-26[soc-custom-26]
	database[database]
	soc-custom-29[soc-custom-29]
	soc-custom-6-software[soc-custom-6-software]
	soc-custom-15-software[soc-custom-15-software]
	soc-custom-20[soc-custom-20]
	soc-light[soc-light]
	soc-custom-44-software[soc-custom-44-software]
	soc-custom-23[soc-custom-23]
	soc-custom-24[soc-custom-24]
	soc-custom-21[soc-custom-21]
	soc-custom-22[soc-custom-22]
	cloud-printer[cloud-printer]
	soc-custom-39-software[soc-custom-39-software]
	soc-custom-4-software[soc-custom-4-software]
	soc-custom-42-software[soc-custom-42-software]
	soc-custom-36-software[soc-custom-36-software]
	soc-motion[soc-motion]
	soc-humidity-software[soc-humidity-software]
	soc-custom-45-software[soc-custom-45-software]
	cloud-notification-software[cloud-notification-software]
	soc-humidity[soc-humidity]
	soc-alarm-software[soc-alarm-software]
	soc-custom-7-software[soc-custom-7-software]
	server[server]
	cloud-notification[cloud-notification]
	soc-custom-17-software[soc-custom-17-software]
	soc-custom-2-software[soc-custom-2-software]
	soc-light-software[soc-light-software]
	soc-custom-23-software[soc-custom-23-software]
	soc-custom-9-software[soc-custom-9-software]
	soc-smoke[soc-smoke]
	soc-gate-software[soc-gate-software]
	soc-custom-47-software[soc-custom-47-software]
	soc-custom-12-software[soc-custom-12-software]
	soc-temperature[soc-temperature]
	soc-custom-50-software[soc-custom-50-software]
	soc-custom-41-software[soc-custom-41-software]
	soc-custom-19-software[soc-custom-19-software]
	soc-custom-13-software[soc-custom-13-software]
	soc-custom-28-software[soc-custom-28-software]
	soc-custom-22-software[soc-custom-22-software]
	soc-custom-50[soc-custom-50]
	iot-controller-software[iot-controller-software]
	soc-custom-31-software[soc-custom-31-software]
	soc-custom-40-software[soc-custom-40-software]
	iot-controller[iot-controller]
	soc-custom-14-software[soc-custom-14-software]
	soc-temperature-software[soc-temperature-software]
	soc-custom-37-software[soc-custom-37-software]
	soc-custom-32-software[soc-custom-32-software]
	router[router]
	cloud-printer-software[cloud-printer-software]
	cloud-weather-software[cloud-weather-software]
	soc-smoke-software[soc-smoke-software]
	soc-custom-21-software[soc-custom-21-software]
	soc-custom-38-software[soc-custom-38-software]
	soc-custom-27-software[soc-custom-27-software]
	soc-custom-33-software[soc-custom-33-software]
	soc-custom-24-software[soc-custom-24-software]
	soc-custom-18-software[soc-custom-18-software]
	soc-custom-1-software[soc-custom-1-software]
	soc-custom-38[soc-custom-38]
	soc-custom-39[soc-custom-39]
	soc-door-lock-software[soc-door-lock-software]
	soc-custom-36[soc-custom-36]
	soc-custom-37[soc-custom-37]
	soc-custom-48-software[soc-custom-48-software]
	soc-custom-30[soc-custom-30]
	soc-custom-31[soc-custom-31]
	soc-custom-34[soc-custom-34]
	soc-custom-35[soc-custom-35]
	soc-custom-32[soc-custom-32]
	soc-custom-33[soc-custom-33]
	soc-door-lock[soc-door-lock]
	soc-custom-11-software[soc-custom-11-software]
	soc-motion-software[soc-motion-software]
	soc-custom-46-software[soc-custom-46-software]
	soc-gate[soc-gate]
	cloud-weather[cloud-weather]
	soc-custom-8-software[soc-custom-8-software]
	soc-custom-49[soc-custom-49]
	soc-custom-35-software[soc-custom-35-software]
	soc-custom-47[soc-custom-47]
	soc-custom-48[soc-custom-48]
	desktop[desktop]
	server-software[server-software]
	soc-custom-5[soc-custom-5]
	soc-custom-41[soc-custom-41]
	soc-custom-42[soc-custom-42]
	soc-custom-6[soc-custom-6]
	soc-custom-3[soc-custom-3]
	printer-software[printer-software]
	soc-custom-29-software[soc-custom-29-software]
	soc-custom-4[soc-custom-4]
	soc-custom-40[soc-custom-40]
	soc-custom-1[soc-custom-1]
	soc-custom-45[soc-custom-45]
	soc-custom-30-software[soc-custom-30-software]
	soc-custom-2[soc-custom-2]
	soc-custom-46[soc-custom-46]
	soc-custom-43[soc-custom-43]
	soc-custom-44[soc-custom-44]
	soc-custom-3-software[soc-custom-3-software]
	printer --> printer-software
	printer --> router
	soc-custom-9 --> soc-custom-9-software
	soc-custom-9 --> iot-controller
	soc-custom-7 --> soc-custom-7-software
	soc-custom-7 --> iot-controller
	soc-custom-8 --> soc-custom-8-software
	soc-custom-8 --> iot-controller
	soc-custom-10-software --> soc-custom-10
	soc-custom-10-software --> database
	soc-custom-16 --> soc-custom-16-software
	soc-custom-16 --> iot-controller
	soc-custom-17 --> soc-custom-17-software
	soc-custom-17 --> iot-controller
	soc-custom-14 --> soc-custom-14-software
	soc-custom-14 --> iot-controller
	soc-custom-15 --> soc-custom-15-software
	soc-custom-15 --> iot-controller
	soc-custom-16-software --> soc-custom-16
	soc-custom-16-software --> database
	soc-alarm --> soc-alarm-software
	soc-alarm --> iot-controller
	soc-custom-18 --> soc-custom-18-software
	soc-custom-18 --> iot-controller
	soc-custom-19 --> soc-custom-19-software
	soc-custom-19 --> iot-controller
	soc-custom-12 --> soc-custom-12-software
	soc-custom-12 --> iot-controller
	soc-custom-25-software --> soc-custom-25
	soc-custom-25-software --> database
	soc-custom-13 --> soc-custom-13-software
	soc-custom-13 --> iot-controller
	soc-custom-34-software --> soc-custom-34
	soc-custom-34-software --> database
	soc-custom-10 --> soc-custom-10-software
	soc-custom-10 --> iot-controller
	soc-custom-11 --> soc-custom-11-software
	soc-custom-11 --> iot-controller
	soc-custom-43-software --> soc-custom-43
	soc-custom-43-software --> database
	soc-custom-5-software --> soc-custom-5
	soc-custom-5-software --> database
	soc-custom-20-software --> soc-custom-20
	soc-custom-20-software --> database
	soc-custom-26-software --> soc-custom-26
	soc-custom-26-software --> database
	soc-custom-49-software --> soc-custom-49
	soc-custom-49-software --> database
	soc-custom-27 --> soc-custom-27-software
	soc-custom-27 --> iot-controller
	soc-custom-28 --> soc-custom-28-software
	soc-custom-28 --> iot-controller
	soc-custom-25 --> soc-custom-25-software
	soc-custom-25 --> iot-controller
	desktop-software --> desktop
	soc-custom-26 --> soc-custom-26-software
	soc-custom-26 --> iot-controller
	database --> iot-controller
	database --> iot-controller-software
	database --> soc-motion-software
	database --> soc-humidity-software
	database --> soc-door-lock-software
	database --> soc-gate-software
	database --> soc-alarm-software
	database --> soc-smoke-software
	database --> soc-temperature-software
	database --> soc-light-software
	database --> server-software
	database --> soc-custom-1-software
	database --> soc-custom-2-software
	database --> soc-custom-3-software
	database --> soc-custom-4-software
	database --> soc-custom-5-software
	database --> soc-custom-6-software
	database --> soc-custom-7-software
	database --> soc-custom-8-software
	database --> soc-custom-9-software
	database --> soc-custom-10-software
	database --> soc-custom-11-software
	database --> soc-custom-12-software
	database --> soc-custom-13-software
	database --> soc-custom-14-software
	database --> soc-custom-15-software
	database --> soc-custom-16-software
	database --> soc-custom-17-software
	database --> soc-custom-18-software
	database --> soc-custom-19-software
	database --> soc-custom-20-software
	database --> soc-custom-21-software
	database --> soc-custom-22-software
	database --> soc-custom-23-software
	database --> soc-custom-24-software
	database --> soc-custom-25-software
	database --> soc-custom-26-software
	database --> soc-custom-27-software
	database --> soc-custom-28-software
	database --> soc-custom-29-software
	database --> soc-custom-30-software
	database --> soc-custom-31-software
	database --> soc-custom-32-software
	database --> soc-custom-33-software
	database --> soc-custom-34-software
	database --> soc-custom-35-software
	database --> soc-custom-36-software
	database --> soc-custom-37-software
	database --> soc-custom-38-software
	database --> soc-custom-39-software
	database --> soc-custom-40-software
	database --> soc-custom-41-software
	database --> soc-custom-42-software
	database --> soc-custom-43-software
	database --> soc-custom-44-software
	database --> soc-custom-45-software
	database --> soc-custom-46-software
	database --> soc-custom-47-software
	database --> soc-custom-48-software
	database --> soc-custom-49-software
	database --> soc-custom-50-software
	soc-custom-29 --> soc-custom-29-software
	soc-custom-29 --> iot-controller
	soc-custom-6-software --> soc-custom-6
	soc-custom-6-software --> database
	soc-custom-15-software --> soc-custom-15
	soc-custom-15-software --> database
	soc-custom-20 --> soc-custom-20-software
	soc-custom-20 --> iot-controller
	soc-light --> soc-light-software
	soc-light --> iot-controller
	soc-custom-44-software --> soc-custom-44
	soc-custom-44-software --> database
	soc-custom-23 --> soc-custom-23-software
	soc-custom-23 --> iot-controller
	soc-custom-24 --> soc-custom-24-software
	soc-custom-24 --> iot-controller
	soc-custom-21 --> soc-custom-21-software
	soc-custom-21 --> iot-controller
	soc-custom-22 --> soc-custom-22-software
	soc-custom-22 --> iot-controller
	cloud-printer --> cloud-printer-software
	cloud-printer --> router
	soc-custom-39-software --> soc-custom-39
	soc-custom-39-software --> database
	soc-custom-4-software --> soc-custom-4
	soc-custom-4-software --> database
	soc-custom-42-software --> soc-custom-42
	soc-custom-42-software --> database
	soc-custom-36-software --> soc-custom-36
	soc-custom-36-software --> database
	soc-motion --> soc-motion-software
	soc-motion --> iot-controller
	soc-humidity-software --> soc-humidity
	soc-humidity-software --> database
	soc-custom-45-software --> soc-custom-45
	soc-custom-45-software --> database
	cloud-notification-software --> cloud-notification
	cloud-notification-software --> iot-controller-software
	soc-humidity --> soc-humidity-software
	soc-humidity --> iot-controller
	soc-alarm-software --> soc-alarm
	soc-alarm-software --> database
	soc-custom-7-software --> soc-custom-7
	soc-custom-7-software --> database
	server --> server-software
	cloud-notification --> cloud-notification-software
	cloud-notification --> router
	soc-custom-17-software --> soc-custom-17
	soc-custom-17-software --> database
	soc-custom-2-software --> soc-custom-2
	soc-custom-2-software --> database
	soc-light-software --> soc-light
	soc-light-software --> database
	soc-custom-23-software --> soc-custom-23
	soc-custom-23-software --> database
	soc-custom-9-software --> soc-custom-9
	soc-custom-9-software --> database
	soc-smoke --> soc-smoke-software
	soc-smoke --> iot-controller
	soc-gate-software --> database
	soc-gate-software --> soc-gate
	soc-custom-47-software --> soc-custom-47
	soc-custom-47-software --> database
	soc-custom-12-software --> soc-custom-12
	soc-custom-12-software --> database
	soc-temperature --> soc-temperature-software
	soc-temperature --> iot-controller
	soc-custom-50-software --> soc-custom-50
	soc-custom-50-software --> database
	soc-custom-41-software --> soc-custom-41
	soc-custom-41-software --> database
	soc-custom-19-software --> soc-custom-19
	soc-custom-19-software --> database
	soc-custom-13-software --> soc-custom-13
	soc-custom-13-software --> database
	soc-custom-28-software --> soc-custom-28
	soc-custom-28-software --> database
	soc-custom-22-software --> soc-custom-22
	soc-custom-22-software --> database
	soc-custom-50 --> soc-custom-50-software
	soc-custom-50 --> iot-controller
	iot-controller-software --> iot-controller
	iot-controller-software --> database
	iot-controller-software --> cloud-weather-software
	iot-controller-software --> cloud-notification-software
	soc-custom-31-software --> soc-custom-31
	soc-custom-31-software --> database
	soc-custom-40-software --> soc-custom-40
	soc-custom-40-software --> database
	iot-controller --> iot-controller-software
	iot-controller --> database
	iot-controller --> soc-motion
	iot-controller --> soc-humidity
	iot-controller --> soc-door-lock
	iot-controller --> soc-alarm
	iot-controller --> soc-smoke
	iot-controller --> soc-light
	iot-controller --> router
	iot-controller --> desktop
	iot-controller --> soc-custom-1
	iot-controller --> soc-custom-2
	iot-controller --> soc-custom-3
	iot-controller --> soc-custom-4
	iot-controller --> soc-custom-5
	iot-controller --> soc-custom-6
	iot-controller --> soc-custom-7
	iot-controller --> soc-custom-8
	iot-controller --> soc-custom-9
	iot-controller --> soc-custom-10
	iot-controller --> soc-custom-11
	iot-controller --> soc-custom-12
	iot-controller --> soc-custom-13
	iot-controller --> soc-custom-14
	iot-controller --> soc-custom-15
	iot-controller --> soc-custom-16
	iot-controller --> soc-custom-17
	iot-controller --> soc-custom-18
	iot-controller --> soc-custom-19
	iot-controller --> soc-custom-20
	iot-controller --> soc-custom-21
	iot-controller --> soc-custom-22
	iot-controller --> soc-custom-23
	iot-controller --> soc-custom-24
	iot-controller --> soc-custom-25
	iot-controller --> soc-custom-26
	iot-controller --> soc-custom-27
	iot-controller --> soc-custom-28
	iot-controller --> soc-custom-29
	iot-controller --> soc-custom-30
	iot-controller --> soc-custom-31
	iot-controller --> soc-custom-32
	iot-controller --> soc-custom-33
	iot-controller --> soc-custom-34
	iot-controller --> soc-custom-35
	iot-controller --> soc-custom-36
	iot-controller --> soc-custom-37
	iot-controller --> soc-custom-38
	iot-controller --> soc-custom-39
	iot-controller --> soc-custom-40
	iot-controller --> soc-custom-41
	iot-controller --> soc-custom-42
	iot-controller --> soc-custom-43
	iot-controller --> soc-custom-44
	iot-controller --> soc-custom-45
	iot-controller --> soc-custom-46
	iot-controller --> soc-custom-47
	iot-controller --> soc-custom-48
	iot-controller --> soc-custom-49
	iot-controller --> soc-custom-50
	iot-controller --> soc-temperature
	iot-controller --> soc-gate
	soc-custom-14-software --> soc-custom-14
	soc-custom-14-software --> database
	soc-temperature-software --> database
	soc-temperature-software --> soc-temperature
	soc-custom-37-software --> soc-custom-37
	soc-custom-37-software --> database
	soc-custom-32-software --> soc-custom-32
	soc-custom-32-software --> database
	router --> iot-controller
	router --> printer
	router --> cloud-printer
	router --> cloud-weather
	router --> cloud-notification
	cloud-printer-software --> cloud-printer
	cloud-printer-software --> printer-software
	cloud-weather-software --> cloud-weather
	cloud-weather-software --> iot-controller-software
	soc-smoke-software --> soc-smoke
	soc-smoke-software --> database
	soc-custom-21-software --> soc-custom-21
	soc-custom-21-software --> database
	soc-custom-38-software --> soc-custom-38
	soc-custom-38-software --> database
	soc-custom-27-software --> soc-custom-27
	soc-custom-27-software --> database
	soc-custom-33-software --> soc-custom-33
	soc-custom-33-software --> database
	soc-custom-24-software --> soc-custom-24
	soc-custom-24-software --> database
	soc-custom-18-software --> soc-custom-18
	soc-custom-18-software --> database
	soc-custom-1-software --> soc-custom-1
	soc-custom-1-software --> database
	soc-custom-38 --> soc-custom-38-software
	soc-custom-38 --> iot-controller
	soc-custom-39 --> soc-custom-39-software
	soc-custom-39 --> iot-controller
	soc-door-lock-software --> soc-door-lock
	soc-door-lock-software --> database
	soc-custom-36 --> soc-custom-36-software
	soc-custom-36 --> iot-controller
	soc-custom-37 --> soc-custom-37-software
	soc-custom-37 --> iot-controller
	soc-custom-48-software --> soc-custom-48
	soc-custom-48-software --> database
	soc-custom-30 --> soc-custom-30-software
	soc-custom-30 --> iot-controller
	soc-custom-31 --> soc-custom-31-software
	soc-custom-31 --> iot-controller
	soc-custom-34 --> soc-custom-34-software
	soc-custom-34 --> iot-controller
	soc-custom-35 --> soc-custom-35-software
	soc-custom-35 --> iot-controller
	soc-custom-32 --> soc-custom-32-software
	soc-custom-32 --> iot-controller
	soc-custom-33 --> soc-custom-33-software
	soc-custom-33 --> iot-controller
	soc-door-lock --> soc-door-lock-software
	soc-door-lock --> iot-controller
	soc-custom-11-software --> soc-custom-11
	soc-custom-11-software --> database
	soc-motion-software --> soc-motion
	soc-motion-software --> database
	soc-custom-46-software --> soc-custom-46
	soc-custom-46-software --> database
	soc-gate --> soc-gate-software
	soc-gate --> iot-controller
	cloud-weather --> cloud-weather-software
	cloud-weather --> router
	soc-custom-8-software --> soc-custom-8
	soc-custom-8-software --> database
	soc-custom-49 --> soc-custom-49-software
	soc-custom-49 --> iot-controller
	soc-custom-35-software --> soc-custom-35
	soc-custom-35-software --> database
	soc-custom-47 --> soc-custom-47-software
	soc-custom-47 --> iot-controller
	soc-custom-48 --> soc-custom-48-software
	soc-custom-48 --> iot-controller
	desktop --> desktop-software
	desktop --> iot-controller
	server-software --> server
	server-software --> database
	soc-custom-5 --> soc-custom-5-software
	soc-custom-5 --> iot-controller
	soc-custom-41 --> soc-custom-41-software
	soc-custom-41 --> iot-controller
	soc-custom-42 --> soc-custom-42-software
	soc-custom-42 --> iot-controller
	soc-custom-6 --> soc-custom-6-software
	soc-custom-6 --> iot-controller
	soc-custom-3 --> soc-custom-3-software
	soc-custom-3 --> iot-controller
	printer-software --> printer
	printer-software --> cloud-printer-software
	soc-custom-29-software --> soc-custom-29
	soc-custom-29-software --> database
	soc-custom-4 --> soc-custom-4-software
	soc-custom-4 --> iot-controller
	soc-custom-40 --> soc-custom-40-software
	soc-custom-40 --> iot-controller
	soc-custom-1 --> soc-custom-1-software
	soc-custom-1 --> iot-controller
	soc-custom-45 --> soc-custom-45-software
	soc-custom-45 --> iot-controller
	soc-custom-30-software --> soc-custom-30
	soc-custom-30-software --> database
	soc-custom-2 --> soc-custom-2-software
	soc-custom-2 --> iot-controller
	soc-custom-46 --> soc-custom-46-software
	soc-custom-46 --> iot-controller
	soc-custom-43 --> soc-custom-43-software
	soc-custom-43 --> iot-controller
	soc-custom-44 --> soc-custom-44-software
	soc-custom-44 --> iot-controller
	soc-custom-3-software --> soc-custom-3
	soc-custom-3-software --> database