%% AttributeChange [4mcontiki-ng/contiki-ng[0m to [4m4.7[0m for node [4miot-controller[0m
%%  VOID -[1,00]->  iot-controller -[1,00]->  soc-motion -[0,08]-> soc-motion-software 3,96 0,08
flowchart LR
	iot-controller[iot-controller]
	soc-motion[soc-motion]
	soc-motion-software[soc-motion-software]
	VOID[VOID]
	iot-controller -->|!firewall-risk 0,80| soc-motion
	iot-controller -->|!physically-secured-risk 0,80| soc-motion
	iot-controller -->|!software-encrypted-risk 0,80| soc-motion
	iot-controller -->|!CVE-2022-25666 0,08| soc-motion
	iot-controller -->|!CVE-2022-35927 0,39| soc-motion
	soc-motion -->|!CVE-2022-25666 0,08| soc-motion-software
	VOID -->|!uncertainty-entry 0,08| iot-controller
	VOID -->|!firewall-risk 0,80| iot-controller
	VOID -->|!physically-secured-risk 0,80| iot-controller
	VOID -->|!software-encrypted-risk 0,80| iot-controller
	VOID -->|!CVE-2022-35927 0,39| iot-controller