%% AttributeChange [4msoftwareComponentIsEncrypted[0m to [4mtrue[0m for node [4msoc-door-lock[0m
%%  VOID -[0,71]->  iot-controller -[0,88]->  soc-door-lock -[0,08]-> soc-door-lock-software 20,12 0,05
flowchart LR
	soc-door-lock[soc-door-lock]
	soc-door-lock-software[soc-door-lock-software]
	iot-controller[iot-controller]
	VOID[VOID]
	soc-door-lock -->|!CVE-2022-25666 0,08| soc-door-lock-software
	iot-controller -->|hasFirewall 0,20| soc-door-lock
	iot-controller -->|isPhysicallySecured 0,20| soc-door-lock
	iot-controller -->|!software-encrypted-risk 0,80| soc-door-lock
	iot-controller -->|!CVE-2022-25666 0,08| soc-door-lock
	VOID -->|!uncertainty-entry 0,08| iot-controller
	VOID -->|hasFirewall 0,20| iot-controller
	VOID -->|isPhysicallySecured 0,20| iot-controller
	VOID -->|softwareComponentIsEncrypted 0,20| iot-controller
	VOID -->|!CVE-2022-35927 0,39| iot-controller