%% AttributeChange [4mqualcom/apq8096[0m to [4m2.1[0m for node [4msoc-humidity[0m
%%  VOID -[0,93]->  iot-controller -[0,98]->  soc-humidity -[0,08]-> soc-humidity-software 3,65 0,07
flowchart LR
	iot-controller[iot-controller]
	soc-humidity-software[soc-humidity-software]
	soc-humidity[soc-humidity]
	VOID[VOID]
	iot-controller -->|hasFirewall 0,20| soc-humidity
	iot-controller -->|!physically-secured-risk 0,80| soc-humidity
	iot-controller -->|!software-encrypted-risk 0,80| soc-humidity
	iot-controller -->|!CVE-2022-25666 0,08| soc-humidity
	iot-controller -->|!CVE-2022-35927 0,39| soc-humidity
	soc-humidity -->|!CVE-2022-25666 0,08| soc-humidity-software
	VOID -->|!uncertainty-entry 0,08| iot-controller
	VOID -->|hasFirewall 0,20| iot-controller
	VOID -->|isPhysicallySecured 0,20| iot-controller
	VOID -->|!software-encrypted-risk 0,80| iot-controller
	VOID -->|!CVE-2022-35927 0,39| iot-controller