%% AttributeChange [4mqualcom/apq8096[0m to [4m2.1[0m for node [4msoc-humidity[0m
%%  VOID -[0,71]->  soc-gate -[0,93]->  iot-controller -[1,00]->  soc-humidity -[0,08]-> soc-humidity-software 2,63 0,05
flowchart LR
	iot-controller[iot-controller]
	soc-humidity-software[soc-humidity-software]
	soc-gate[soc-gate]
	soc-humidity[soc-humidity]
	VOID[VOID]
	iot-controller -->|!firewall-risk 0,80| soc-humidity
	iot-controller -->|!physically-secured-risk 0,80| soc-humidity
	iot-controller -->|!software-encrypted-risk 0,80| soc-humidity
	iot-controller -->|!CVE-2022-25666 0,08| soc-humidity
	iot-controller -->|!CVE-2022-35927 0,39| soc-humidity
	soc-gate -->|hasFirewall 0,20| iot-controller
	soc-gate -->|isPhysicallySecured 0,20| iot-controller
	soc-gate -->|!software-encrypted-risk 0,80| iot-controller
	soc-gate -->|!CVE-2022-25666 0,08| iot-controller
	soc-gate -->|!CVE-2022-35927 0,39| iot-controller
	soc-humidity -->|!CVE-2022-25666 0,08| soc-humidity-software
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|isPhysicallySecured 0,20| soc-gate
	VOID -->|softwareComponentIsEncrypted 0,20| soc-gate
	VOID -->|!CVE-2022-35927 0,39| soc-gate