%% AttributeChange [4mcontiki-ng/contiki-ng[0m to [4m4.7[0m for node [4mserver[0m
%%  VOID -[1,00]->  server -[0,08]-> server-software 3,98 0,08
flowchart LR
	server[server]
	server-software[server-software]
	VOID[VOID]
	server -->|!CVE-2022-25666 0,08| server-software
	VOID -->|!uncertainty-entry 0,08| server
	VOID -->|!firewall-risk 0,80| server
	VOID -->|!physically-secured-risk 0,80| server
	VOID -->|!software-encrypted-risk 0,80| server
	VOID -->|!CVE-2022-35927 0,39| server