%% AttributeChange [4mcontiki-ng/contiki-ng[0m to [4m4.7[0m for node [4msoc-gate[0m
%%  VOID -[0,97]->  soc-gate -[0,08]-> soc-gate-software 23,29 0,08
flowchart LR
	soc-gate-software[soc-gate-software]
	soc-gate[soc-gate]
	VOID[VOID]
	soc-gate -->|!CVE-2022-25666 0,08| soc-gate-software
	VOID -->|!uncertainty-entry 0,08| soc-gate
	VOID -->|hasFirewall 0,20| soc-gate
	VOID -->|!physically-secured-risk 0,80| soc-gate
	VOID -->|!software-encrypted-risk 0,80| soc-gate