%% AttributeChange [4mcontiki-ng/contiki-ng[0m to [4m4.7[0m for node [4msoc-motion[0m
%%  VOID -[0,53]->  iot-controller -[0,53]->  soc-motion -[0,08]-> soc-motion-software 1,12 0,02
flowchart LR
	iot-controller[iot-controller]
	soc-motion[soc-motion]
	soc-motion-software[soc-motion-software]
	VOID[VOID]
	iot-controller -->|hasFirewall 0,20| soc-motion
	iot-controller -->|isPhysicallySecured 0,20| soc-motion
	iot-controller -->|softwareComponentIsEncrypted 0,20| soc-motion
	iot-controller -->|!CVE-2022-25666 0,08| soc-motion
	soc-motion -->|!CVE-2022-25666 0,08| soc-motion-software
	VOID -->|!uncertainty-entry 0,08| iot-controller
	VOID -->|hasFirewall 0,20| iot-controller
	VOID -->|isPhysicallySecured 0,20| iot-controller
	VOID -->|softwareComponentIsEncrypted 0,20| iot-controller